feat: 비밀번호 재설정 페이지 퍼블리싱
shophubkr/shophub-client pull request #12
Opened 2023-08-16 00:27 UTC by Doeunnkimm

# Describe your changes

- 비밀번호 재설정 페이지에 chakra를 적용하여 기초 퍼블리싱을 마무리했습니다.

## Issue ticket number and link (optional)

#7 

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

- 디자인 시스템에 맞는 UI 적용 작업이 추후에 필요할 것 같습니다.

## Screenshots (optional)

<img width="1509" alt="image" src="https://github.com/shophubkr/shophub-client/assets/112946860/5f50388b-050a-4d2f-966b-f478cecdd43b">

## Questions

- 💬 질문 사항이에요!
apps 디렉토리에서 packages 디렉토리에 있는 훅 함수 등을 사용하려면 어떻게 해야할까요..!?
바로 사용하려고 했더니 useShophubTheme() 경로를 못 찾는 것 같아 여쭤봅니다..!

- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-08-16 12:49 UTC, minsoo-web requested changes
리뷰 남깁니다~!
그리고 import 는 

<img width="503" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/a4c01ae8-0ece-4b4f-af67-fb2a451f0623">

가져오고 싶은 packages의 package.json에 명시된 name 값을 적고
버전을 workspace:^ 라고 적으면 됩니다.

2023-08-16 12:49 UTC, minsoo-web commented on apps/client/src/app/auth/forget-password/page.tsx
> +        <Center flexDir="column" mt="16px" w="312px" gap="32px">
32px이 아니라 48px 같습니다!

2023-08-16 12:49 UTC, minsoo-web commented on apps/client/src/app/auth/forget-password/page.tsx
> +          <Button w="full">재설정 링크</Button>
이메일에 맞는 정규식이 아니면 비활성화 되어있는 디자인 같은데 맞는지 확인이 필요해보이긴합니다. 
도은님이 태찬님께 한 번 물어봐주세요, disabled 라는 상태 값이 없네요 버튼 컴포넌트에

2023-08-20 13:10 UTC, Doeunnkimm commented on apps/client/src/app/auth/forget-password/page.tsx
> +        <Center flexDir="column" mt="16px" w="312px" gap="32px">
[fix: 비밀번호 재설정 페이지 스타일 일부 수정](https://github.com/shophubkr/shophub-client/pull/12/commits/aeed59b70b9f6414a7cb914c34f71d71076a923c)

스타일 수정 했습니다 !

2023-08-31 16:45 UTC, minsoo-web approved these changes

2023-08-31 16:46 UTC, merged