#5 MSW 환경 설정을 합니다.
shophubkr/shophub-client pull request #13
Opened 2023-08-16 13:25 UTC by showme0241

# Describe your changes
msw 환경 설정을 마무리합니다.

## Issue ticket number and link (optional)
#5 

## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
msw의 모의 api를 통한 테스트 진행

## Screenshots (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

💬 react 환경과 비교했을 때, msw를 사용하는데 차이가 있다거나 참고해야할 사항이 있나요?

2023-08-16 15:27 UTC, minsoo-web requested changes
<img width="938" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/6485bed3-5181-4978-96bd-f8e72ccd74c3">

충돌 해결 부탁드립니다!

사실 이번 #5 이슈는 msw 환경 세팅까지만 이라서, 회원가입 mock api는 리뷰 범위가 아닌 것 같긴합니다.
우선 충돌해결해주시고 PR 업데이트 부탁드릴게요!

2023-08-16 15:27 UTC, minsoo-web commented on apps/client/src/app/provider.tsx
이미 provider가 main에 있어서요! 충돌해결 후 업데이트 부탁드립니다 ㅎㅎ

2023-08-16 15:27 UTC, minsoo-web commented on apps/client/src/mocks/Apis/sign/signApi.ts
회원가입 api 인터페이스는 백엔드분들이랑 모두 소통이 된 걸까요..?! 제가 놓치고 있는건지 아니면 태찬님이 이렇게 줘야 할 것 같다, 라고 생각하고 만드신건지 궁금합니다!

2023-08-16 15:27 UTC, minsoo-web commented on apps/client/src/mocks/Apis/sign/signResponse.ts
이 부분도 마찬가지로, 백엔드 분들이랑 협의가 된 내용들인지 궁금합니다!
만약 아니라면 msw를 사용하는 의미가 퇴색되거든요 ㅠㅠ

2023-08-16 15:27 UTC, minsoo-web commented on apps/client/src/mocks/Apis/sign/signResponse.ts
협의가 된 내용이라 함은,

회원가입 할 때 이런 이런 정보들을 post 요청으로 payload에 담아주시고,
에러 케이스는 ~~한 케이스들이 있고  각각 status는 다음과 같습니다.

라는 소통이 있으셨는지가 궁금합니다.

2023-08-16 23:56 UTC, showme0241 commented on apps/client/src/app/provider.tsx
네 ! 충돌 해결하고 업데이트 해놓았습니다 !

2023-08-16 23:59 UTC, showme0241 commented on apps/client/src/mocks/Apis/sign/signApi.ts
아뇨 없었습니다 srs 참고해서 임의적으로 만들었습니다. ㅠㅠ
사실 제가 가늠한 환경 설정의 범위가 msw 작동과 테스트라고 생각하는 바람에 필요외 고민과 코드가 생긴 것같습니다.

2023-08-17 00:02 UTC, showme0241 commented on apps/client/src/mocks/Apis/sign/signResponse.ts
아 죄송해요 ㅠㅠ 협의사항은 없었습니다 ㅠ
mock 기반으로 작동이 잘되는지 테스트를 해야겠다는 생각에 임의적으로 생긴 것 같아요 ㅠ

💬 Apis 폴더는 delete하고 다시 업데이트 해놓을까요?

2023-08-17 01:13 UTC, minsoo-web commented on apps/client/src/mocks/Apis/sign/signResponse.ts
이미 만드신 내용이니까 지우실 필요는 없을 것 같습니다! msw 를 활용해서 api 연동 테스트를 할 때 백엔드 분들과 협의 후 작업 진행하면 될 것 같습니다!

2023-08-17 01:14 UTC, minsoo-web approved these changes

2023-08-17 01:14 UTC, merged