#4 회원가입 플로우를 퍼블리싱 합니다.
shophubkr/shophub-client pull request #14
Opened 2023-08-17 00:26 UTC by showme0241

# Describe your changes
회원가입 플로우를 퍼블리싱 합니다.

## Issue ticket number and link (optional)
#4 

## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [ ] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
rules 패턴 적용(+정규식), msw 테스트, 사업자 조회 모달

## Screenshots (optional)
![step1_entry](https://github.com/shophubkr/shophub-client/assets/77373566/9c54d5a9-e9d4-4676-b666-5df4d8602909)
![step1_choiceUser_buyer](https://github.com/shophubkr/shophub-client/assets/77373566/05594949-c93d-4c93-8421-d5533000e170)
![step2_choiceUser_buyer](https://github.com/shophubkr/shophub-client/assets/77373566/c88f7852-cf9b-47ba-9bfb-070bd5331b6a)
![step1_choiceUser_seller](https://github.com/shophubkr/shophub-client/assets/77373566/aca53146-fb04-4089-855a-ce455fbb23cd)
![step2_choiceUser_seller](https://github.com/shophubkr/shophub-client/assets/77373566/1ba5ac78-17c1-4a1d-bf52-760ce26d01c9)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

🔥mock api 활용을 해야한다고 생각해버려서 퍼블리싱 범위를 넘어선 코드가 많은 것 같습니다. 앞으로는 이처럼 예외 케이스가 생길 경우에는 민수님께 말씀드리고 하겠습니다 !

2023-08-17 01:41 UTC, minsoo-web requested changes
변경사항이 많아서 리뷰를 1차로 한 번 나누겠습니다! 리뷰 한 번 확인해주세요!

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +};
styles 파일을 따로 만들어서 관리하는게 나을 것 같아요!
그리고 styled component 하나를 선언할 때마다, export const 로 선언하고 import 할 때 
import * as S from "./Foo.styles.ts"

이렇게 하면 될 것 같습니다.
그리고 S는 약어니까, Styled 라고 조금 길더라고 제대로 적는 게 좋을 것 같습니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +  }
이렇게 작성하면 결국 컴파일된 css 파일은 태그 선택자를 사용하게 되는데요, 태그 선택자를 활용하면 안 되는 이유에 대해서 혹시 아시나요?

컴파일된 css는 다음과 같은 형태를 갖게됩니다.

```css
.emotion-foo > label {
  display: flex;
}
```

css는 브라우저가 파싱할 때, 선택자를 오른쪽 -> 왼쪽 순서로 읽습니다.
태그 선택자를 먼저 만난 브라우저는 dom에 사용된 모든 태그를 찾고, 그 다음 부모 선택자로 넘어가는 순서로 찾게 됩니다.
불필요하게 많은 일을 브라우저에게 시키는 것보다는 필요한 작업만 시키는 것이 좋기 때문에 태그 선택자는 최대한 지양하는 습관이 좋습니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +  children: string | JSX.Element;
PropsWithChildren 을 활용하시면 됩니다!

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +export default function CheckElement({ field, children }: CheckEleProps) {
Element라는 건 불필요한 suffix 같아요.
그리고 한글로 직역하면 "체크요소" 로 번역되는데, 

체크박스라는 공통 컴포넌트를 만드는 게 맞아보입니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +  margin-bottom: 8px;
체크 박스가 항상 margin-bottom을 가지는 게 아니라, checkbox를 불러오는 요소에서 간격을 조정하도록 처리하는 게 맞습니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +  margin-bottom: 8px;
부르는 코드에서 gap: 8px 을 명시하면 되겠죠 ?

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +    onBlur: () => void;
VoidFunction 이라는 타입이 있는데, 활용해보시면 좋을 것 같아요!
기능이나 동작하는 건 아예 똑같이 동작합니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +export const Label: Record<string, string> = {
타입 선언 안 해도 되는 것 같은데 필요한 타입 선언인가요?

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +  const [isBusiness, setIsBusiness] = useState(false);
boolean 타입 보다는, signUpType 이라는 타입을 따로 만드시고,
"buyer" | "seller"
라고 나누는 게 더 직관적인 것 같습니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +  };
이 부분은 2차 리뷰 때 언급드릴게요! 우선은 1차 리뷰에 남긴 내용 반영을 먼저 해주세요!

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +export const Label: Record<string, string> = {
label을 여기서 상수로 관리하는 게 아니라, FormElement 라는 컴포넌트의 props로 받아서 처리하는 게 낫습니다. 
나중에 label을 수정해야 한다는 가정이 생겼을 때 모든 요소가 이 상수 객체 하나에 영향을 받아버리니, string 인자 값으로 받게 독립적으로 관리하는 게 낫습니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +      {name !== "passwordConfirm" && <p>{Label[name]} *</p>}
이 부분도 label이 있으면 보여줘, 라는 걸로 처리하면 되겠죠?!

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +    <S.Wrapper style={{ marginBottom: name === "password" ? "8px" : "40px" }}>
간격은 자식 요소가 직접 컨트롤하는게 아니라, 부르는 부모 입장에서 간격을 조정하는 게 관리하기 쉽습니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +        )}
사업자번호 양식이라면 조회버튼을 생성하는 로직이 모든 formElement에 필요할까요?
사업자 번호 양식을 위한 컴포넌트를 분리하는 게 좋아보입니다. 
지금은 이 컴포넌트가 너무 많은 역할을 하고 있어서 제어문이 불가피해집니다.

하나의 form 요소만 추가되더라도 얼마나 많은 것들을 신경써야 하는지 감이 안 옵니다. 
너무 많은 일을 하나의 컴포넌트에 시키게 되면 번거롭게 처리해야 하는 경우가 많기 때문에, 독립적인 컴포넌트로 관리를 용이하게 하는 것도 방법입니다.

2023-08-17 01:41 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +  }
간격을 자식입장에서 하지 않고, 부모에게 gap으로 처리하면 이런 코드가 없어질 것 같습니다

2023-08-17 01:44 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +};
넵 ! 확인했습니다 답변 감사합니다 !

2023-08-17 01:47 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +  }
아... 몰랐습니다 좋은 정보 감사합니다 앞으로 참고하여 태그 선택자는 지양하겠습니다 !

2023-08-17 01:50 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +export default function CheckElement({ field, children }: CheckEleProps) {
넵넵 ! 체크박스와 텍스트 요소를 같이 묶어야된다고 생각하다보니 Element를 사용한 것 같습니다.
수정 해놓도록 하겠습니다 !

2023-08-17 01:51 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +  margin-bottom: 8px;
아 그러네요... 생각이 짧았습니다 ! 감사합니다. 👍

2023-08-17 01:54 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +export const Label: Record<string, string> = {
아... 맞네요 이것 또한 생각이 짧았던 것 같습니다 ㅠ 답변 감사합니다 !

2023-08-17 01:54 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +      {name !== "passwordConfirm" && <p>{Label[name]} *</p>}
넵 !

2023-08-17 01:56 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +    <S.Wrapper style={{ marginBottom: name === "password" ? "8px" : "40px" }}>
넵 ! 감사합니다 ! 👍

2023-08-17 01:59 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +        )}
넵 ! 말씀주신대로 독립적으로 관리하는게 좋아보입니다 ! 수정해놓도록 하겠습니다 !

2023-08-17 02:05 UTC, Doeunnkimm reviewed
저도 몇 가지 리뷰 남겨봅니당

2023-08-17 02:05 UTC, Doeunnkimm commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +export default function FormElement({ field, errors }: FormEleProps) {
Named export 방식으로 변경되어야 할 것 같습니다! 약속한대로!

2023-08-17 02:05 UTC, Doeunnkimm commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +      {errors && name !== "password" && <S.ErrorMsg>{errors}</S.ErrorMsg>}
password인 경우는 왜 제외시키셨는지 궁금합니다! 
비밀번호도 정규식 패턴에 맞지 않을 경우 에러 메세지를 보여주어야하지 않을까 생각이 들어 여쭤봅니다.

2023-08-17 02:05 UTC, Doeunnkimm commented on apps/client/src/app/auth/signup/step1/page.tsx
> +  const [choiceUser, setChoiceUser] = useState({ userType: "" });
state이름 자체가 choiceUser인데 상태를 한번더 왜 객체 형태로 관리하셨는지도 궁금합니다!

오히려 'seller' | 'buyer'로 유니온 타입을 주어서 상태를 선언하는 것이 나아보이기도 합니다!

2023-08-17 02:05 UTC, Doeunnkimm commented on apps/client/src/app/auth/signup/step2/page.tsx
> +export default function SignUpSecond() {
여기도 마찬가지로 Named export !!

2023-08-17 02:12 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +export default function FormElement({ field, errors }: FormEleProps) {
넵 ! 맞습니다 ! 전부 수정해놓도록 하겠습니다. :)

2023-08-17 02:15 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +      {errors && name !== "password" && <S.ErrorMsg>{errors}</S.ErrorMsg>}
아 이것은 비밀번호와 비밀번호 확인 영역의 UI가 붙어있는 상태라 에러 메시지가 겹쳐버리더 라구요.
그래서 임시방편으로 제외해두고 퍼블리싱을 했었습니다 !

더 나은 방법이 있다면 알려주시면 감사하겠습니다. :)

2023-08-17 02:24 UTC, showme0241 commented on apps/client/src/app/auth/signup/step1/page.tsx
> +  const [choiceUser, setChoiceUser] = useState({ userType: "" });
아 이것은 step2에서 post로 서버에 전송되어야 할 정보이기 때문에 객체 형태로 만들었습니다 !
하지만 query로 보내는 데이터를 객체로 생성하고 있어서 도은님이 이야기해주신대로 변경하면 좋을 것 같습니다 감사합니다 !

2023-08-17 07:31 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +  children: string | JSX.Element;
💬 children으로 전달된 값의 타입으로 설정한다는 뜻인가요?

2023-08-17 09:27 UTC, showme0241 commented on apps/client/src/app/auth/signup/step2/page.tsx
> +export default function SignUpSecond() {
page.tsx 파일이여서 default가 필요하다고 합니다 ㅠㅠ

2023-08-17 10:08 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +    onBlur: () => void;
엇 ! 숨겨져있던 리뷰입니다 넵 감사합니다. :)

2023-08-17 10:12 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +export const Label: Record<string, string> = {
Label[name]으로 접근할 때, field으로 전달되는 name이 string이다 보니깐 key에 접근하고, value를 취할 때 사용되는 타입이라고 하여 취했었습니다 !

밑에 민수님이 리뷰 주신 내용을 바탕으로 아예 지워 버렸습니다. :)

2023-08-17 10:14 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +  };
넵 !

2023-08-17 10:28 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +  const [isBusiness, setIsBusiness] = useState(false);
엇 ! isBusiness는 사업자 번호 존재 여부에 따라 핸들링되는 값입니다 ! 혹시 signUpType이라고 리뷰 주신 내용 어떤 느낌인지는 알 것 같은데 조금 설명해주실수 있을까요? ㅠ

2023-08-17 16:54 UTC, Doeunnkimm reviewed
리뷰 남깁니당

2023-08-17 16:54 UTC, Doeunnkimm commented on apps/client/src/app/auth/signup/step1/page.tsx
> +  const [choiceUser, setChoiceUser] = useState<string>("");
```suggestion
const [choiceUser, setChoiceUser] = useState<'buyer' | 'seller'| null>(null);
```
으로 하고, 필요할 때 null을 가드해 버리는 게 좀 더 명확하다는 생각이 듭니다 😃

2023-08-17 16:54 UTC, Doeunnkimm commented on apps/client/src/app/auth/signup/step2/page.tsx
> +          />
[재사용 가능한 Controller Input](https://velog.io/@boyeon_jeong/React-Hook-Form-Controller-useController-y6v2mfc9#2-custom-hook-%EC%82%AC%EC%9A%A9-usecontroller-%EC%B6%94%EC%B2%9C) 만드는 걸 활용해 본 적이 있는데 좋은 것 같더라구요!

적용해 보시면 훨씬 깔끔해질 것 같아요!

2023-08-17 16:54 UTC, Doeunnkimm commented on apps/client/src/app/auth/signup/step2/page.tsx
> +            rules={{ required: "비밀번호를 입력해주세요." }}
그리고 제가 저번에 잠깐 말씀드렸던 yup 사용하시면 매 필드마다 rules를 적어주지 않아도 name이랑 연결되어서 쉽고 편한 유효성 검사가 가능하더라구요!

yup도 알아보시면 좋을 것 같아요 😄 !

2023-08-18 09:31 UTC, showme0241 commented on apps/client/src/app/auth/signup/step1/page.tsx
> +  const [choiceUser, setChoiceUser] = useState<string>("");
와우... 너무 좋습니다 감사합니다 !

2023-08-18 09:33 UTC, showme0241 commented on apps/client/src/app/auth/signup/step2/page.tsx
> +          />
공유해주신 문서 일부 훑어봤는데 너무 좋습니다 !! 안 그래도 코드가 길어져서 마음에 들지 않았는데 감사합니다 도은님 최고에요 👍👍👍👍👍

2023-08-18 09:34 UTC, showme0241 commented on apps/client/src/app/auth/signup/step2/page.tsx
> +            rules={{ required: "비밀번호를 입력해주세요." }}
넵 ! 윱윱 한 번 알아보겠습니다 좋은 정보 감사합니다 ! 보고 모르는게 있으면 물어볼게요 !

2023-08-20 11:52 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/CheckElement.tsx
> +  children: string | JSX.Element;
아 아뇨아뇨 react에서 제공하는 제네릭 타입인데, 아래와 같이 사용하시면 됩니다.

<img width="539" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/e8e87760-eda4-40cf-9918-51f5707c1c62">

2023-08-20 11:55 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +  const [isBusiness, setIsBusiness] = useState(false);
아 사업자 번호 존재 여부에 따른거라면 좀 더 명확한 변수명이 나을 것 같아요
isBusiness 만으로는 유추하기가 어려운 것 같아요, 이럴 땐 차라리 한글 변수명이 낫습니다.

```
const [사업자번호가있는가, set사업자번호여부] = useState(false);
```

2023-08-20 12:32 UTC, minsoo-web requested changes
2차 리뷰 남깁니다

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
> +import { Button } from "~/components/Button/Button";
배럴파일이라는 걸 만들어주세요
index.ts 형태의 파일입니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
> +        `https://api.odcloud.kr/api/nts-businessman/v1/status?serviceKey=jLYDm8UrTI6O0xwYjloDybofTULlg9YFEVIbA8pyRkS78TmOmeB%2B%2FlVlBWBqqoOtBAiEn%2FyukJGWMuMJrMdt0w%3D%3D`,
api 통신하는 함수는 따로 정리해주세요.

auth/_state/server/api.ts 파일에 정리해주세요

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
> +        `https://api.odcloud.kr/api/nts-businessman/v1/status?serviceKey=jLYDm8UrTI6O0xwYjloDybofTULlg9YFEVIbA8pyRkS78TmOmeB%2B%2FlVlBWBqqoOtBAiEn%2FyukJGWMuMJrMdt0w%3D%3D`,
axios 호출 응답 결과를 제네릭으로 추론하는 방법이 있습니다. 한 번 찾아보시고 적용해보세요!

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
> +`;
<img width="813" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/0afb8687-b16b-4306-a253-6365d879d191">

태그선택자로 초기화되어있던데 필요한 초기화 속성값인가요? 모든 버튼이 margin-top이 필요하지 않는데 정의가 되어있어서 이렇게 불필요하게 사용하는 쪽에서 지워줘야 하는 것 같습니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +      {errors && name !== "password" && <S.ErrorMsg>{errors}</S.ErrorMsg>}
제 생각엔
<img width="382" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/c7fcd499-e3ff-448b-965e-1ca5a23eeb0e">

이 ui에서 사람들이 비밀번호 확인 input이라고 당연하게 생각하지 않을 것 같은데,, 어떻게 생각하시나요?!

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +      {errors && name !== "password" && <S.ErrorMsg>{errors}</S.ErrorMsg>}
ui 자체를 개선하면 어떨지 의견 드려봅니다

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +`;
global css에 정의된 button의 margin top을 지우고 이런 초기화 하는 애들을 지워주세요!

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +const StyledBtn = styled(Button)`
style 관련된 애들은 styles.ts 에서 정의하기로 컨벤션 정한걸로 기억합니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step1/page.tsx
> +  const onUserType = (e: React.MouseEvent<HTMLButtonElement>) => {
const onClickUserType = (userType: "buyer" | "seller") => {
  setChoiceUser(userType)
}

으로 하면 안 되나요?
너무 불필요하게 많은 텍스트 제어문으로 인해 가독성이 떨어집니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step1/page.tsx
> +  const [choiceUser, setChoiceUser] = useState<string>("");
choiceUser 가 직역하면

선택 유저

인데,
userChoice
signUpUserType
userType

이 가독성 측면에서 더 나은 것 같습니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step1/page.tsx
> +const Wrapper = styled.section`
styles.ts 파일 생성해서 관리해주세요

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step2/page.tsx
> +import { BusinessApiButton } from "../../_components/Form/BusinessApiButton";
typescript에서 pathAlias 라는 설정이 있습니다.

<img width="1331" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/2c5f16cf-72f9-4caf-81e4-b970c75926c1">

이렇게 하면 도메인 별로 복잡한 상대경로를 사용하지 않아도 됩니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step2/page.tsx
> +import { FormElement } from "../../_components/Form/FormElement";
배럴파일을 만들어서 import 경로를 깔끔하게 정리해보세요

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step2/page.tsx
> +  const userType = searchParams.get("userType");
<img width="330" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/5ac76e39-778b-4c38-8e30-98e0aa0efcd2">

이 방식 어떠신가요 next/navigation 에서 import 할 수 있습니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step2/page.tsx
> +  }, [router]);
필요한 코드인가요..?!

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step2/page.tsx
> +  const onSubmitHandler = async (data: any) => {
any말고 타입을 지정해주세요

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/auth/signup/step2/page.tsx
이 파일이 너무 많은 역할을 하고 있습니다. userType에 따라 다른 컴포넌트로 분리하고 공통 분모만 뽑아서 props로 전달해주세요

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/globals.css
> +}
왜 퍼센트로 했는지 궁금합니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/globals.css
> +  padding: 0 16px;
모든 input에 공통으로 들어가게 됩니다. 지양해주세요.
input 공통컴포넌트가 만들어졌을 때 거기에 선언하면 됩니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/globals.css
>  }
태찬님이 만드신 디자인을 기반으로 작업해서 이런 것도 방법이긴 하지만, (내가 만든 버튼은 모두 이러니까 이렇게 써도 돼)
태그 선택자는 언제 어떻게 사용될지 모릅니다. 초기화를 하는 것 외에는 global.css 에 지정하면 안 됩니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/globals.css
> +section {
이것도 마찬가지로 사용하는 곳에서 지정해야 하는 코드 같습니다. layout 에서 지정하면 되는 거라고 생각합니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/globals.css
> +h6 {
타이포그래피에서 지정하고 생성된 컴포넌트로 관리되어야 하는 속성 같습니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/app/globals.css
> +.material-icons + p {
어떨 때 사용되나요? 사용되는 곳에서 gap 을 줘야 한다고 생각합니다.

2023-08-20 12:32 UTC, minsoo-web commented on apps/client/src/components/Button/Button.tsx
> +export interface ButtonProps {
얘도 PropsWithChildren으로 개선해보세요~!

2023-08-20 14:00 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +  const [isBusiness, setIsBusiness] = useState(false);
한글로 써본다는 생각은 해본적이 없는데 좋습니다 ! 감사합니다 !

2023-08-20 14:04 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +      {errors && name !== "password" && <S.ErrorMsg>{errors}</S.ErrorMsg>}
넵 좋습니다! 피그마 수정해두었습니다. :)

2023-08-20 14:22 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
> +import { Button } from "~/components/Button/Button";
항상 잘 가르쳐주셔서 감사합니다 !
이거 정말 좋은 것 같아요 ! 세팅해두었습니다 👍

2023-08-20 14:23 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
> +        `https://api.odcloud.kr/api/nts-businessman/v1/status?serviceKey=jLYDm8UrTI6O0xwYjloDybofTULlg9YFEVIbA8pyRkS78TmOmeB%2B%2FlVlBWBqqoOtBAiEn%2FyukJGWMuMJrMdt0w%3D%3D`,
넵! 알겠습니다 감사합니다 ! 찾아보고 이해 안되는 게 있으면 여쭤보겠습니다 !

2023-08-20 15:50 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +      {errors && name !== "password" && <S.ErrorMsg>{errors}</S.ErrorMsg>}
개선된 ui로 업데이트 완료했습니다. :)

2023-08-20 15:51 UTC, showme0241 commented on apps/client/src/app/auth/signup/step2/page.tsx
> +          />
useController 오늘 씨름하다가 아까 풀려서 드디어 리팩토링 완료! 도은님한테 박수 👏 👏 👏

2023-08-20 15:52 UTC, showme0241 commented on apps/client/src/app/auth/signup/step1/page.tsx
> +  const [choiceUser, setChoiceUser] = useState<string>("");
넵 userChoice로 choice 했습니다 !ㅎㅎ

2023-08-20 15:53 UTC, showme0241 commented on apps/client/src/app/auth/signup/step2/page.tsx
> +  const userType = searchParams.get("userType");
react라는 구성이 다르네요 ㅎㅎ 반영시켜놓았습니다. :)

2023-08-20 15:57 UTC, showme0241 commented on apps/client/src/app/auth/signup/step2/page.tsx
> +  }, [router]);
불필요한 코드입니다 ! 
userType에 따라 step2에서 ui가 달라져야하는데 초반에 리렌더가 안 되는 현상이 있었어서 작업 도중에 세팅해둔 코드였습니다 !

2023-08-20 15:58 UTC, showme0241 commented on apps/client/src/app/auth/signup/step2/page.tsx
> +  const onSubmitHandler = async (data: any) => {
넵 ! 이것도 commit하기전에 바꿔놓고 올렸어야했는데 깜빡했습니다ㅠㅠ 타입 설정해두었습니다 !

2023-08-22 13:53 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
> +`;
대부분의 버튼 margin-top을 갖고 있는 경우라고 생각이 듭니다 ! 하지만 사용되는 케이스에 따라 달라지는 값이라 초기값으로 설정하는 것은 불필요하다고 생각합니다 !

2023-08-22 13:54 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/BusinessApiButton.tsx
> +`;
다만, 의문이 드는 것은 사용하는 케이스에 따라 margin-top이 차이가 있는데  컴포넌트 별로 전부 지정해줘야하는 걸까 입니다.

2023-08-22 13:55 UTC, showme0241 commented on apps/client/src/app/auth/_components/Form/FormElement.tsx
> +`;
넵 ! 알겠습니다. :)

2023-08-22 14:13 UTC, showme0241 commented on apps/client/src/app/globals.css
> +}
퍼블리싱 반응형 작업에 습관이 있어... rem을 사용하기 위해 초반에 설정된 값입니다. 

as-is : 100% => 1rem = 16px
to-be : 62.5% => 1rem = 10px

하지만 전역 스타일 구성은 모바일 환경에 맞게 픽스될 부분이라 rem으로 변경시킬 이유가 없지 않을까 생각됩니다.

2023-08-22 14:13 UTC, showme0241 commented on apps/client/src/app/globals.css
>  }
네 알겠습니다 ! 감사합니다. :)

2023-08-22 14:32 UTC, showme0241 commented on apps/client/src/app/auth/signup/step1/page.tsx
> +  const onUserType = (e: React.MouseEvent<HTMLButtonElement>) => {
넵 ! 가능합니다 ! 수정하였습니다 !

2023-08-31 16:50 UTC, minsoo-web approved these changes

2023-08-31 16:50 UTC, merged