feat: Modal UI 모듈화를 마무리합니다.
shophubkr/shophub-client pull request #16
Opened 2023-08-18 14:58 UTC by Doeunnkimm

# Describe your changes

- Modal 컴포넌트 추가
- context와 hook 함수 이용해서 모듈화
- storybook으로 사용 방법 및 UI Story 구현

추가로,
- [figma](https://www.figma.com/file/RPPVjNjpaD6bxNDSc0p5Vo/%EC%82%AC%EC%9D%B4%EB%93%9C-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%3A-%23%ED%97%88%EB%B8%8C_ProtoType?type=design&node-id=82-463&mode=design&t=gSJ9DVREIE6rkltL-0) 바탕으로 color token 추가
- storybook에서 google material icon 쓸 수 있도록 세팅

## Issue ticket number and link (optional)

#7 

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Screenshots (optional)

![shophub_1](https://github.com/shophubkr/shophub-client/assets/112946860/6591a297-9147-41a0-9de1-bade96db7b27)

<img width="1506" alt="image" src="https://github.com/shophubkr/shophub-client/assets/112946860/9b4b61fe-7824-41b4-9ea2-89842c356cc0">

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-08-20 13:25 UTC, minsoo-web requested changes
리뷰 남깁니다~!

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.stories.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
필요한 주석인가요?
<img width="436" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/8c75d9c0-a9ee-49d2-8432-4be4c4a7f18a">

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.stories.tsx
> +};
args는 함수 선언 안에서 직접하는게 좋습니다.

기능적인 차이는 아니고, 스토리별로 모아서 한 눈에 볼 수 있기 때문에, args를 따로 작성하지 마시고 스토리 안에 속성으로 넣어주세요

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +  z-index: 1;
zag 포탈을 사용하기 때문에 z-index를 높일 필요가 없어보이는데, 필요한가요??

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +  bottom: 0;
6개중 두 개가 필요 없는 애인데, 뭐인지 맞춰보세요

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +export const Wrapper = styled.div`
무슨 Wrapper일까요? 화면을 보면서 코드를 짜는 습관보다, 코드만 봐도 무슨 역할인지 알아볼 수 있게 짜는 게 가장 좋습니다.

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +  z-index: 2;
필요한가요? 지워보니까 어 필요없네, 가 아니라
왜 불필요한 코드이고, 왜 적으려고 했는지를 설명해봐주세요

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +export const Container = styled.div`
어떤 걸 container라고 부르고 어떤걸 wrapper라고 부르고 어떤걸 Box라고 부르나요? 

<img width="221" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/fa3df740-dc6d-4c7b-81d2-255b70925d40">

이 화면과 함수 이름만 봤을 때 유추가 가능하신가요..?!

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +export const BtnWrap = styled.section`
제가 저번 리뷰에 안 남겼는지 모르겠지만, 저는 개인적으로 btn 과 같이 유명한 약어를 쓰는 걸 별로 안 좋아합니다. 

예) btn, e, i, el
-> button, event, index, element

와 같이 명시적으로 적어주는 것이 조금 길더라도 가독성을 해치지 않는다고 생각합니다.

모르는 사람에게는 생각을 한 번 더 하게 한다는 점에서 단점이고, 
축약은 어차피 자동완성을 지원해주기 때문에, 굳이 변수명이 길어진다고 해서 불편하게 느껴지지 않을 것 같습니다.

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +export const BtnWrap = styled.section`
<img width="183" alt="image" src="https://github.com/shophubkr/shophub-client/assets/57122180/024285a9-145b-4a2d-b73c-3873c28e10da">

간격이 필요한 것 같은데, 없어도 될까요?

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.tsx
> +                  )}
이 부분을 컴포넌트로 추상화를 한 번 더 하는 게 좋을 것 같아요, 지금 이 컴포넌트의 역할은 모달을 띄우고 각 요소별 배치를 정하는 것에만 집중하게 하고, 

안에 세부 내용은 props로 전달받아서 추상화를 시켜주면 가독성 및 유지보수에 강점이 생길 것 같습니다.

ModalBody / ModalFooter 등의 네이밍으로 추상화 해서 만들어보세요

```
<ModalBody text={text} />
<ModalFooter onConfirm={...} />
```

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.types.ts
> +  text: string;
text는 어떤 텍스트인지 감이 안 올 것 같습니다.
title이 좀 더 직관적이지 않나요?
아니면 mainText 와 같은 건 어떠신지 의견 듣고 싶습니다.

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/hooks/useModal.tsx
> +    throw new Error("onOpenModal is not working.");
not working 보다는 provider가 필요하다, 라고 적는게 더 명확할 것 같습니다.

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/context/ModalContext.tsx
> +};
제 개인적인 생각으로는 isOpen과 props를 구분짓는 게 더 나아보여요
props에 isOpen을 넣어주지 않는데, 얘네 둘을 합치니까 불필요하게 많은 처리가 부가적으로 생기는 것 같습니다.

2023-08-20 13:25 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.stories.tsx
> +Positive.args = {
만드시는 김에 다른 버전들도 만들어보세요!!

2023-08-20 13:29 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.stories.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
엇 필요할까봐 포함했는데 지우도록 하겠습니다 🙂

2023-08-20 14:05 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.styles.ts
> +  bottom: 0;
width, height가 필요없습니다....🫢

2023-08-20 14:39 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.styles.ts
> +  z-index: 2;
1. z-index에 관해
      ark-ui의 Potal 컴포넌트에 대해 제대로 이해를 잘 못 했던 상황에서, 기존에 모달 만드는 습관이 들어갔던 것 같습니다..!
      
      [실제 Portal 컴포넌트 코드](https://github.com/chakra-ui/zag/blob/main/packages/frameworks/react/src/portal.ts#L18C1-L18C1)를 살펴보니 자신의 상위 위치의 DOM에 element를 생성하고 자신을 child로 추가합니다.
      
      직접 테스트해보니 자식 컴포넌트와 부모 컴포넌트 모두에게 z-index를 부여하지 않으며 두 컴포넌트가 동일한 위치와 크기의 컴포넌트를 화면에 렌더링하게 된다면, 자식 컴포넌트의 요소가 더 위 레이어에 위치하게 되는 것을 확인했습니다.
  
      따라서 Portal 컴포넌트를 사용할 경우 z-index를 사용해 레이어의 순서를 굳이 부여해 줄 필요가 없다고 판단할 수 있었습니다.

2. position: relative에 관해
  relative는 보통 부모 컴포넌트를 정적 위치로 잡아놓고 그 위치를 기준으로 이동을 시켜야 하는 경우에 사용합니다. 그런데 Modal 컴포넌트에서는 부모 컴포넌트에서 flex를 통해 가운데에 정렬해 놓았기 떄문에 불필요합니다.

2023-08-20 15:33 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.stories.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
[chore: 불필요한 주석 delete](https://github.com/shophubkr/shophub-client/pull/16/commits/643f6ba74825b7531c0d245c30b4819ff354a53a)

주석 제거했습니다 👍!

2023-08-20 15:35 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.stories.tsx
> +};
[chore: args 속성들을 스토리 안으로 포함되도록 리팩터링](https://github.com/shophubkr/shophub-client/pull/16/commits/9baea8b03e60305a73d435ad76f6ca440a468312)

같은 스토리를 가리키고 있다는 걸 한번에 확인할 수 있어서 더 좋은 방법인 것 같습니다. 좋은 리뷰 남겨주셔서 감사해요! 👍!

2023-08-20 15:38 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.styles.ts
> +  z-index: 1;
[chore: 불필요하거나 더 필요한 스타일 속성 수정 및 추가](https://github.com/shophubkr/shophub-client/pull/16/commits/03d7b2916ccfb869222a8e15b7a7c25063f42a2b)

Portal 컴포넌트를 더 잘 알고나니 필요없을 것 같습니다 🫨 수정했습니다!

2023-08-20 15:39 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.styles.ts
> +  bottom: 0;
[chore: 불필요하거나 더 필요한 스타일 속성 수정 및 추가](https://github.com/shophubkr/shophub-client/pull/16/commits/03d7b2916ccfb869222a8e15b7a7c25063f42a2b)

없어도 동일하게 렌더링되는 거 확인하고 수정했습니다!

2023-08-20 15:40 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.styles.ts
> +export const Wrapper = styled.div`
[chore: 불필요하거나 더 필요한 스타일 속성 수정 및 추가](https://github.com/shophubkr/shophub-client/pull/16/commits/03d7b2916ccfb869222a8e15b7a7c25063f42a2b)

ModalWrapper로 변경했습니다.

2023-08-20 15:42 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.styles.ts
> +export const Container = styled.div`
[chore: 불필요하거나 더 필요한 스타일 속성 수정 및 추가](https://github.com/shophubkr/shophub-client/pull/16/commits/03d7b2916ccfb869222a8e15b7a7c25063f42a2b)

Wrapper -> ModalWrapper
Container -> Body
BtnWrap -> ButtonWrap

위와 같이 컴포넌트 명 수정했습니다. 코드만 봐도 무슨 역할일 수 있도록 짜는 거 명심하겠습니다..!!!! 🙌

2023-08-20 15:44 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.styles.ts
> +export const BtnWrap = styled.section`
[chore: 불필요하거나 더 필요한 스타일 속성 수정 및 추가](https://github.com/shophubkr/shophub-client/pull/16/commits/03d7b2916ccfb869222a8e15b7a7c25063f42a2b#diff-408c7f5da5474356eee9ac141e8198499aa95a6acc3581633672d6bafec6a0aaR47)

피그마에 기재된 내용으로는 여전히 조금 답답한 느낌이 있어, 태찬님과 상의 후 21px로 적용했습니다!

2023-08-20 15:47 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.types.ts
> +  text: string;
[chore: ModalProps에서 text -> title (직관적일 수 있도록 변경)](https://github.com/shophubkr/shophub-client/pull/16/commits/d0740f6792669cbceed468bc3a3ef7753558e40a)

민수님 말씀대로 title이 좀 더 직관적인 것 같습니다..!!! 적용했습니다 :)

2023-08-20 15:48 UTC, Doeunnkimm commented on packages/ui/src/Modal/hooks/useModal.tsx
> +    throw new Error("onOpenModal is not working.");
[chore: useModal 미동작 시의 에러 메세지 수정](https://github.com/shophubkr/shophub-client/pull/16/commits/15580d0ae8170785c8676a0778a651f1f628305f)

"useModal should be used within ModalContext.Provider"로 수정했습니다 :-)

2023-08-21 04:36 UTC, Doeunnkimm commented on packages/ui/src/Modal/context/ModalContext.tsx
> +};
[chore: ModalProps를 isOpen, props, onClose로 구분](https://github.com/shophubkr/shophub-client/pull/16/commits/8fcd9f4eac93be06aae3a907723cd03801032b12)

말씀해주신 내용 정말 좋은 것 같습니다!!!! 
추가로, onClose도 provider를 통해서만 전달받는 prop이라 isOpen, props: { type, title, onConfirm }, onClose로 구분되도록 했습니다!

추가로 궁금한 점도 있는데요!
이제 props가 객체 형태라 스토리북에서 props 내부에 있는 프로퍼티들을 control할 수 있는 방법도 있을까요?..!

2023-08-21 04:41 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.tsx
> +                  )}
[chore: Modal 내부 추상화 (ModalBody, ModalFooter)](https://github.com/shophubkr/shophub-client/pull/16/commits/da47f0020ed425271385980720d75a14db37321e)

세부 내용 추상화 시켜주었습니다!! 수정하면서 훨씬 가독성 및 유지보수에 좋을 것 같다는 생각이 들었습니다 👍 감사합니다!

2023-08-21 05:44 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.stories.tsx
> +Positive.args = {
[feat: Modal 관련 스토리 추가 (Negative, Warning)](https://github.com/shophubkr/shophub-client/pull/16/commits/2d5b1f336d516b798f6fb2e68b8c8ea187df7072)

Negative, Warning 버전도 추가했습니다!

2023-08-31 16:56 UTC, minsoo-web requested changes
주석 관련된 리뷰 하나만 봐주시구 충돌 수정해주세요~!

2023-08-31 16:56 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.stories.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
오잉 저는, eslint 주석이 없어져도 에러가 안 나는 걸 스크린샷찍어본겁니다!!

2023-08-31 16:56 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.stories.tsx
> +    onClose: () => {},
요론 애는 줘도 그만 안 줘도 그만이긴 합니다!
storybook 에서 편하게 수정하기가 어려워서, 개발단에서 필요하면 넣어보는 형태로 처리하는 경우가 많아요

2023-08-31 16:56 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.stories.tsx
> +  render: (args) => <Modal {...args} />,
이거 자체가 필요 없지 않나요? 🤔

2023-08-31 16:56 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +  align-items: center;
저희 flex 유틸 함수가 없군요,, 만들어두면 좋긴한데, 우선은 넘어갑시다!!

2023-09-01 05:29 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.stories.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
[chore: 불필요한 eslint 주석 제거](https://github.com/shophubkr/shophub-client/pull/16/commits/32af1ae837f015c26f5f1627d670263ec50810dd)
엇 맞습니다..!!! 제거했습니다 👍

2023-09-01 05:29 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.stories.tsx
> +  render: (args) => <Modal {...args} />,
[chore: 없어도 되는 render 프로퍼티 제거](https://github.com/shophubkr/shophub-client/pull/16/commits/528176e02905ff2d72781d8623ffa56262374f99)

넵!! 제거했습니다!

2023-09-01 05:36 UTC, Doeunnkimm commented on packages/ui/src/Modal/Modal.styles.ts
> +  align-items: center;
엇 제가 만들고 리팩터링 바로 해놓아도 괜찮을 거 같은데, 보통 어떤 폴더에서 작업하게 되나요 !?
추가로 스타일 관련 유틸 함수 만들 때 특별히 요구사항 같은 게 있을까요?

2023-09-02 14:36 UTC, minsoo-web commented on packages/ui/src/Modal/Modal.styles.ts
> +  align-items: center;
디자인 시스템 제공하는 패키지에서 보통 같이 작업합니다~! 이번 PR 말고 다른 작업에서 같이 하시죠! 범위가 너무 커질 것 같습니다

2023-09-02 14:37 UTC, minsoo-web approved these changes

2023-09-02 14:37 UTC, merged