회원 가입 플로우에 Api를 적용하여 업데이트 합니다.
shophubkr/shophub-client pull request #26
Opened 2023-12-04 13:59 UTC by showme0241

# Describe your changes

- [delete] 사용하지 않는 컴포넌트 삭제 <사업자 진위 여부 조회>
- [update] Yup 라이브러리 기반 유효성 검사 처리
- [delete] 공용 컴포넌트 FormElement의 사용하지 않는 props 삭제
- [update] choiceUserType 객체 배열 처리
- [add] axios 인스턴스(=api) 생성
- [add] api 사용 폴더 생성
- [add] usePostUserSignUp mutation 함수 생성
- [add] 외부 워크스페이스 import : nextConfig > transpliePackages 옵션 추가
- [add] ModalProvider import > useModal 훅 사용

## Issue ticket number and link (optional)

#4 

## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [ ] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

- FormElement storybook 문서화 작업
- 스타일링 작업 : color token과 font guide

## Screenshots (optional)

## Questions
🤷‍♂️ 공용 컴포넌트 FormElement : 공통의 값만 props로 핸들링하고, 예외 케이스는 extends해서 사용해도 되는지 확인받고 싶습니다.  [SignUpForm component](https://github.com/shophubkr/shophub-client/blob/97002101c0a79b161f627fc9ddd143d4f360091f/apps/client/src/app/auth/signup/step2/_components/SignUpForm.tsx)가 그 예시 입니다. 참고해서 봐주시면 감사하겠습니다.

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-12-05 02:45 UTC, Doeunnkimm requested changes
태찬님! 우선 1차 리뷰 남깁니다 😀
PR단위가 너무 커서 리뷰하기가 조금 버거웠는데요..! 다음부터는 조금 작게 올려주셨으면 합니다 🙏
사전에 세팅해야 하는 것들에서 의견이 다르면 피드백 받기 전에 해둔 모든 것들을 수정해야 하니까 틈틈이 PR 올려주셨으면 합니다 🥲 저는 언제든지 확인할 수 있거든요 !!

2023-12-05 02:45 UTC, Doeunnkimm commented on apps/client/src/app/_apis/@core.ts
header에 token 심어놓는 로직이 빠진 것 같은데 추가 부탁드립니다 👏

2023-12-05 02:45 UTC, Doeunnkimm commented on apps/client/src/app/_apis/@core.ts
> +export const api = axios.create({
`api`는 뭔가 혼동이 있을 거 같은 네이밍이라고 생각합니다.
만약 매개변수로 지금 auth가 required인지 아닌지 옵션을 받는다고 한다면
`createAxiosInstance` 정도가 될 거 같은데 어떠신가요 ?

2023-12-05 02:45 UTC, Doeunnkimm commented on apps/client/src/app/_apis/apis.ts
혹시 이 파일에 모든 api를 모아두시려는 건가요 ..? 파일명이 `apis`여서 여쭤봅니당

2023-12-05 02:45 UTC, Doeunnkimm commented on apps/client/src/app/_components/Form/FormElement.style.ts
요건 Chakra 통해서도 충분히 가능하지 않나요..? emotion을 사용하신 이유에 대해 궁금합니다

2023-12-05 02:45 UTC, Doeunnkimm commented on apps/client/src/app/auth/_constants/constants/signUp/signUpChoiceUserType.array.ts
> +    id: 1,
여기 id는 왜 들어가는 건가요..? 혹시 map 돌리실 때 key로 사용하시려는 의도셨나요 ?

2023-12-05 02:45 UTC, Doeunnkimm commented on apps/client/src/app/auth/_state/server/hooks/usePostUserSignUp.ts
> +          onConfirm: () => alert("회원가입 완료"),
이 부분에 대해서는 제가 Modal 컴포넌트에 `확인` 버튼만 있어서 눌렀을 때 닫힐 수 있도록 옵션 하나 더 만들어 놓겠습니다 👏

2023-12-05 02:45 UTC, Doeunnkimm commented on apps/client/src/app/auth/signup/step1/_components/ChoiceUserType.tsx
> +}
저희 타입은 파일로 빼기로 했었던 것 같습니다~!

2023-12-05 02:45 UTC, Doeunnkimm commented on apps/client/src/app/auth/signup/step1/_components/ChoiceUserType.tsx
> +  const onClickUserType = (user: "USER_BUYER" | "USER_SELLER") => {
아래 코드를 계속 보니까 `"USER_BUYER" | "USER_SELLER"`라는 유니온 타입이 계속 반복되고 있는 것 같아요.
따로 하나 타입을 만들어서 사용하면 유지보수에도 좋지 않을까요?

2023-12-05 07:17 UTC, showme0241 commented on apps/client/src/app/_apis/@core.ts
회원가입 브랜치여서 token 로직이 없는채로 PR 하였습니다.
feat/login 에서 작업하여 PR하겠습니다!

2023-12-05 07:17 UTC, showme0241 commented on apps/client/src/app/_apis/@core.ts
> +export const api = axios.create({
좋습니다. 맞네요 혼동될 수 있겠습니다 👍

2023-12-05 07:18 UTC, showme0241 commented on apps/client/src/app/_apis/apis.ts
auth쪽으로 넘겨야 하겠습니다!

2023-12-05 07:18 UTC, Doeunnkimm commented on apps/client/src/app/_apis/@core.ts
feat/axios-setting 브랜치에서 처음부터 하셨으면 더 좋았을 거 같다는 생각이 드네용 😂

2023-12-05 07:20 UTC, Doeunnkimm commented on apps/client/src/app/_apis/apis.ts
근데 이 부분은 저번에 파일 컨벤션 이야기를 하다가 제대로 마무리가 안 된 것 같은데
저는 apis 폴더에 다 모아두는 것보다 사용하는 폴더 아래 > states > server > api.ts에서 관리했으면 하는 마음이 있어서요

혹시 어떻게 생각하시나요 ?

2023-12-05 07:20 UTC, showme0241 commented on apps/client/src/app/_components/Form/FormElement.style.ts
Chakra 통해서 충분히 가능합니다.
emotion으로 사용한 별다른 이유는 없습니다. :)

2023-12-05 07:21 UTC, showme0241 commented on apps/client/src/app/auth/_constants/constants/signUp/signUpChoiceUserType.array.ts
> +    id: 1,
맞습니다. 😄

2023-12-05 07:22 UTC, showme0241 commented on apps/client/src/app/auth/signup/step1/_components/ChoiceUserType.tsx
> +  const onClickUserType = (user: "USER_BUYER" | "USER_SELLER") => {
안 그래도 피드백 받고 싶은 부분이었는데 좋습니다.

2023-12-05 07:22 UTC, showme0241 commented on apps/client/src/app/auth/signup/step1/_components/ChoiceUserType.tsx
> +}
아래 리뷰와 함께 처리하도록 하겠습니다! 집어주셔서 감사합니다.

2023-12-05 07:23 UTC, showme0241 commented on apps/client/src/app/_apis/@core.ts
그렇네요 ㅠ

2023-12-05 07:24 UTC, showme0241 commented on apps/client/src/app/_apis/apis.ts
큰 이견은 없습니다! 그렇게 진행하시죠 👍

2023-12-05 07:24 UTC, Doeunnkimm commented on apps/client/src/app/auth/_constants/constants/signUp/signUpChoiceUserType.array.ts
> +    id: 1,
없어도 값 자체가 다른 프로퍼티 이용해서 key 사용하시는 건 어떠신가요? id는 불필요한 프로퍼티 같습니다 🥺

2023-12-05 07:26 UTC, Doeunnkimm commented on apps/client/src/app/_components/Form/FormElement.style.ts
그럼 통일성 있게 Chakra 통해서 하는 게 좋을 거 같습니다!

2023-12-05 07:26 UTC, showme0241 commented on apps/client/src/app/auth/_constants/constants/signUp/signUpChoiceUserType.array.ts
> +    id: 1,
네 수정해놓도록 하겠습니다 감사합니다. 👍

2023-12-05 07:26 UTC, showme0241 commented on apps/client/src/app/_components/Form/FormElement.style.ts
넵!

2023-12-05 07:34 UTC, Doeunnkimm commented on apps/client/src/app/_apis/apis.ts
감사합니다~~🙏

2023-12-05 11:35 UTC, Doeunnkimm commented on apps/client/src/app/_apis/@core.ts
> +export const api = axios.create({
아 추가로, 해당 파일 이름도 왜 @를 붙여서 core라고 표현해야 하는지 설명해주실 수 있나요? 저는 굳이라는 생각이 드네요 🥺 저였다면 그냥 `axios.ts`로 할 것 같아요! 어떠신가요 ?

2023-12-06 13:24 UTC, CodImJun requested changes
리뷰 남깁니다!

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/_apis/@core.ts
> +export const api = axios.create({
저도 core보다는 axios.ts가 낫다고 생각합니다!
core를 파일명으로 해두니 다른 옵션들이 더 들어가야할 것 같은 느낌이에요

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/_apis/apis.ts
그러면 모든 api들은 각 폴더 -> states -> server -> api.ts에서 관리하는걸까요?

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/auth/_constants/constants/signUp/signUpChoiceUserType.array.ts
> +    id: 1,
상수라 대문자로 적어놓는게 어떨까요!

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/auth/_constants/index.ts
다른 배럴파일들은 폴더 경로 ``export * from './_constants/con``로 되어있는데,
이 코드는 설정해두신 path 경로로 되어있어서요! 사소한거지만 컨벤션이 있다면 맞춰도 괜찮을 것 같습니다 :)

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/auth/_constants/validation/signup/validationMsg.ts
이 부분도 SIGN_UP_ERROR_MESSAGE / SIGN_UP_ERR_MSG 처럼 대문자로 바꿔도 좋을 것 같습니다!
저번에 슬랙(?) 보다가 줄임 단어 사용하지 않는다고 봤던 것 같은데 상수는 상관 없는 걸까요?

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/auth/_constants/validation/signup/validationRegex.ts
상수 대문자 의견 동일합니다.

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/auth/_constants/validation/signup/validationSchemas.ts
상수 대문자 의견 동일합니다.

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/auth/_types/signUpType.ts
>    userType?: "buyer" | "seller";
buyer seller 대문자 어떨까요?

2023-12-06 13:24 UTC, CodImJun commented on apps/client/src/app/auth/signup/step1/page.tsx
>        <Flex w="100%" h="149px" columnGap="8px" mt="80px">
Flex Element를 ChoiceUserType 내부에 추가해도 되지 않을까요?

2023-12-08 08:58 UTC, showme0241 commented on apps/client/src/app/_apis/apis.ts
해당 api가 완전 종속된 경우에는 작업 폴더 내에서 처리하는 것이 해당 api를 찾는데 좀 더 수월하지 않을 까 생각됩니다.

2023-12-08 09:03 UTC, showme0241 commented on apps/client/src/app/auth/_constants/index.ts
export from "./~" 으로 해놓는게 빠른 파악이 가능할 것 같아서 수정했습니다.😄
어떠실까요?

2023-12-08 09:05 UTC, showme0241 commented on apps/client/src/app/auth/_constants/validation/signup/validationMsg.ts
상수값은 대문자로 바꾸는게 구분짓는데 좀 더 용이할 것 같습니다.
조금 길어져도 줄임 단어는 피하는게 좋을 것 같은 생각이 있습니다. 어떠실까요?

2023-12-08 09:06 UTC, showme0241 commented on apps/client/src/app/auth/_types/signUpType.ts
>    userType?: "buyer" | "seller";
signUpFormValues에서 userType값이 필요없어서 제거했습니다.
return값이 아닌 submit 전 보강되어야할 값이어서요

2023-12-08 09:06 UTC, showme0241 commented on apps/client/src/app/auth/signup/step1/page.tsx
>        <Flex w="100%" h="149px" columnGap="8px" mt="80px">
네 피드백 주셔서 <Flex></Flex>를 ChoiceUserType 내부에서 작업해두었습니다.
감사합니다. :)

2023-12-08 09:55 UTC, CodImJun commented on apps/client/src/app/auth/_constants/validation/signup/validationMsg.ts
저도 줄임 단어는 피하는게 좋다고 생각합니다!

2024-01-13 14:27 UTC, closed without merging