Detail 페이지 퍼블리싱 1차 마무리
shophubkr/shophub-client pull request #35
Opened 2024-01-11 13:26 UTC by CodImJun

# Describe your changes
- 가게 상세 정보 페이지 퍼블리싱 1차적으로 마무리했습니다.

## Issue ticket number and link (optional)

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Screenshots (optional)

## Questions
- 가게 대표 이미지 슬라이드 이벤트, 쿠폰 리스트는 모달인데 상품 상세 이미지는 페이지로 나뉜 것 등 디자인적 요소들 디자이너분이 한 번 검토해주셔야할 것 같습니다.
- 해당 부분들에 대해서는 작업 중단 상태이고, 나머지 부분은 퍼블리싱 작업 완료했습니다.

2024-01-11 15:13 UTC, Doeunnkimm requested changes
준혁님 고생하셨습니다~!

코드 리뷰하는데에 정말 오래 걸린 거 같아요... 다음에는 더 잘게 쪼개셔서 올려주셔도 됩니다 ㅠㅠ 오히려 적게 자주 보는 게 좋습니다 저는....

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/providers.tsx
> +    </RecoilRoot>
`RecoilRoot`를 가장 바깥쪽에 두신 이유가 있으실까요 ?! 호옥시 모르니까 `QueryClientProvider` 안쪽에 놓는 건 어떠신가요 ?

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/Button/Button.tsx
작업하고 계신 페이지에서 자주 쓰이는 버튼을 모듈화하려고 하신 거 같은데
오히려 공용 컴포넌트로 쓰일 Button을 모듈화하고 그걸 이용하시는 게 훨씬 나을 거 같습니다..!
[figma에 버튼 디자인 시스템](https://www.figma.com/file/RPPVjNjpaD6bxNDSc0p5Vo/shophub-uxui?type=design&node-id=340-393&mode=design&t=eKhFJvvjM6dYIZbu-11)이 존재하니까 요거 참고하셔서 공용 컴포넌트로 만드시면 될 거 같아요. (+ size도 명시되어 있으니 아래 코드에서 case문도 없어질 수 있을 거 같아요)

추가로, 지금 `label === 'share' ? '공유' : 팔로우'` 이런 식의 코드가 많은데 그럼 label이 하나라도 더 늘어나게 되면 구조 자체를 수정해야 하는 일이 있을 것 같습니다. (Button 컴포넌트 모듈화와는 별개로) label로 들어오는 값에 따라 icon과 text를 렌더링하고 싶으신 거라면 객체 구조로 const화 하여 사용하시는 것이 좋을 것 같습니다.

```tsx
// 변수명은 예시일 뿐입니다....주의바람..🙏
const lableToVariants = {
  share: {
    icon: ...
    text: ...
  }
}
```

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
Modal이라고 해놓으셔서 figma에서 어디인지 한참 찾았습니다.....
Modal 보다는 새로고침 해도 유지될 수 있도록 페이지로 라우팅하는 게 좋을 거 같은데 어떠신가요 ?

Modal은 디자인 시스템에 명시되어 있는, 모듈화한 Modal 컴포넌트로만 이용해서 사용하는 걸로 했으면 합니다~~!

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
> +import type { EssentialModalProps } from "@shophub/ui/src/Modal/Modal.types";
참고로, Modal 사용하실 때 Modal import 안 하셔도 됩니다 😭

Modal.stories.tsx 파일 보시면 어떻게 사용하시는지 문서화 되어 있습니다. 혹시라도 나중에 사용하게 되신다면 확인 부탁드립니다.

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +          style={{ font: theme.FONTS.p14r }}
폰트는 next.js 통해서 font optimization 적용하고 charka theme 통해 연결해서 사용하면 될 거 같습니다~~
폰트 관련 부분은 모두 제거해주시고 나중에 추가 작업하시져 ~!

[이거 참고해보셔도 좋을 거 같아요.](https://github.com/chakra-ui/chakra-ui/discussions/7235)

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +          w="100%"
별거 아니지만 `w="full"`로 많이 사용하는 거 같아요! 100%는 !

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/Icon/Icon.constants.ts
Icon 컴포넌트를 모듈화하시려는 이유 알 수 있을까요 ?

제 의견은, 오히려 사용하는 icon이 늘수록 유지보수 하는데 더 오래 걸릴 거 같아요. 또, 이 label을 통해서 아이콘을 찾는 것보다 google material에서 명시해준 이름으로 아이콘을 쓰는 게 더 빠르지 않을까요 ..?

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ProductImage/ProductImage.styles.ts
디자인 시스템에서 이미지 사이즈와 관련된 부분이 없는 것 같은데 사이즈는 준혁님이 지정하신 건가요..?
만약에 나중에 가로세로 `100px` 사이즈로 이미지를 사용하게 되면 유지보수하기에 혼란스러울 거 같습니다...😭

디자인 시스템에 명시되어 있는 것만 사이즈를 사용해주세요 ㅠ ! 다른 개발자가 사용하는 쪽에서 보면 sm이 얼만지 md이 얼만지 모릅니다....😭

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
준혁님 어떤 기준으로 어떤 건 Charka를 사용하시고 어떤 건 emotion을 사용하시는 건가요 ....?

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/Icon/Icon.tsx
Icon 컴포넌트 모듈화하는 건 좋은데 label을 통해서가 아니라 google material에서 명시해주고 있는 named를 통해 컴포넌트를 사용하면 좋을 거 같습니다.

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/Icon/Icon.tsx
> +};
물론 아래 span에 넘겨주는 프로퍼티명은 fontSize지만 사용할 때는 size로 받아도 되지 않을까요?

```suggestion
export const Icon = ({ named, size, color }: IconProps) => {
  return (
    <span className="material-icons-outlined" style={{ fontSize: size, color }}>
      {named}
    </span>
  );
};
```

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/page.tsx
> +import { ShopProductSection } from "./_components/ShopProductSection";
다른 파일들 한번 살펴보시면, 파일마다 `index.ts` 파일이 존재합니다. 베럴 파일이라고 부르는데, `./components` 폴더에서 베럴파일 생성하시고 export 하셔서 사용하셔야 합니다..!

2024-01-11 15:13 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/page.tsx
> +
해당 파일에 있는 중간중간 빈줄은 불필요한 거 같아요 ㅠㅠ

2024-01-11 16:25 UTC, CodImJun commented on apps/client/src/app/providers.tsx
> +    </RecoilRoot>
이유 없습니다! 안쪽에 둘게요

2024-01-11 16:54 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/Button/Button.tsx
버튼 디자인 시스템 봤을 때 공통 컴포넌트에 이점이 없는 디자인이라 생각 했었고,
기존 작성되어 있던 코드를 둘러봤을 때 chakra-ui / Button 이용해서 버튼 컴포넌트를 작성하셔서 일단 제 작업 폴더에 작성했었습니다!
라지 버튼만 봐도 width / height / border-radius / icon 전부 다 다르게 작성이 되는데 공통 컴포넌트로 작성 할 메리트가 있을까요..? ( 단순히 의견이 궁금해서 여쭤봅니다! )
각 버튼들이 쓰이는 페이지가 제한적이면 작업 폴더에 작업해도 되지 않을까 라는 생각입니다.

물론,, 디자이너님께서 들어오셨으니 전체 디자인을 한 번 봐주셔야 될 것 같습니다!
타이포그래피, 컬러 시스템 등 디자인이랑 틀어져있는걸 임의로 맞춰서 코드를 작성한 게 여러번이여서요!

객체 구조 관련 부분 확인했습니다! 감사합니다 :)

2024-01-11 16:56 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
이 부분은 피그마 디자인 상에서 헤더에 뒤로가기 버튼이 아닌 닫기 버튼으로 디자인 되어 있어서 모달로 생각되어 모달로 작성했습니다!
+ 쿠폰은 모달이고, 제품 상세 이미지는 라우팅입니다 ㅎㅎ,,, 이 부분도 회의 때 이야기를 해봐야 할 것 같습니다.

2024-01-11 17:12 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
> +import type { EssentialModalProps } from "@shophub/ui/src/Modal/Modal.types";
Modal import 하지 않으면 Modal is not defined 뜨지 않나요..?
import 하지 않고 사용하는 방법이 어떻게 될까요 ㅠ 코드를 둘러봐도 잘 모르겠네요,,

2024-01-11 17:30 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +          style={{ font: theme.FONTS.p14r }}
이 부분 퍼블리싱 작업도 피그마 디자인이랑 최대한 유사하게 작업하려고 폰트 설정을 해두었습니다.
테마 연결되면 그 후에 작업 하는것이 좋지 않을까요? 해당 작업을 어떤 분이, 어떤 작업 순서로 진행하실 지 모르니까요!

*이모션으로 작성된 폰트 관련 부분도 제거를 생각 하시는 걸까요?

2024-01-11 17:31 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +          w="100%"
다른 코드들에서는 다 px, 숫자로 표현해두어서 100%로 작성했습니다!
full로 작성하는게 보기 더 편할까요?

2024-01-11 17:36 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/Icon/Icon.constants.ts
매번 icon 코드를 작성할 때 마다
```jsx
<span className="material-icons-outlined">
~ 아이콘 이름
</span>
```
을 명시해서 적어주는게 조금 더러워보여서 모듈화 했었는데, 생각해보니 다른 작업자 분들이 보시면 혼란스러울 것 같네요!
이 부분 수정하겠습니다 :)

2024-01-11 17:36 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ProductImage/ProductImage.styles.ts
디자인 시스템에 명시되어있는건 Card UI 뿐이고, 상품 이미지는 디자인 시스템과 관련 없습니다!
이미지 사이즈가 카드랑 상품 이미지 사이즈가 아예 상이합니다.

2024-01-11 17:40 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
<img src="https://github.com/shophubkr/shophub-client/assets/112946860/c5065662-0903-4909-883b-cebd8f2a23f0" width="300"/>

여기가 CouponList 아닌가요..? CouponList로 라우팅 한번더 들어가도 될 거 같은데 어떻게 생각하시나요? 
디자인 시스템에서 명시되어 있는 Modal 하고 달라서 CouponListModal이라는 게 어디있는지 한참 찾았어요 ㅠ..

저는 저 피그마를 몇 달을 봤는데도 `Modal`이라는 키워드 때문에 헤맸던 것 같습니다 ,,ㅠㅠ 나중에 유지보수에 좋지 못한 컴포넌트가 될 것 같습니다ㅠㅠ

2024-01-11 17:44 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
레이아웃(flex, div, etc...)들은 Charka로 작업 했고,
컴포넌트 파일 내에 Charka로 작업하면 코드 줄 수가 길어지는 컴포넌트는 emtion을 사용했습니다.
세부 기준을 세우고 작업 하지는 않았습니다!
해당 기준이 필요하면 회의 때 논의해봐야 할 것 같습니다.

2024-01-11 17:45 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
> +import type { EssentialModalProps } from "@shophub/ui/src/Modal/Modal.types";
```tsx
// Modal.stories.tsx

...
const ModalSample = () => {
  const modal = useModal();

  const onOpenModal = () => {
    modal.open({ type: "positive", title: "테스트 모달입니다.", onConfirm: () => alert("잘 실행되었네요!") });
  };

  return <button onClick={onOpenModal}>누르면 모달이 떠요</button>;
};

export const ButtonToModal: Story = {
  render: () => {
    return (
      <ModalProvider>
        <ModalSample />
      </ModalProvider>
    );
  },
};
```

보시면 최상단에 `ModalProvider` 보이시나요? 저거를 app/provider.tsx`에서 감싸주셔야 합니다~!
감싸시고 

```tsx
const modal = useModal();

const onOpenModal = () => {
  modal.open({ type: "positive", title: "테스트 모달입니다.", onConfirm: () => alert("잘 실행되었네요!") });
};
```
처럼 커스텀 훅 통해 modal 객체 가져오신 다음에 이벤트 함수에서 위처럼 props로 필요한 데이터들 넘기셔서 사용하시면 됩니다!~

2024-01-11 17:46 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +          w="100%"
태찬님도 full로 쓰시는 거 같아요~!

2024-01-11 17:47 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/page.tsx
> +import { ShopProductSection } from "./_components/ShopProductSection";
아 헉 컴포넌트 폴더 내에서 한 번 더 배럴 파일 생성하는걸 생각도 못하고 있었네요,, 감사합니다!

2024-01-11 17:47 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/page.tsx
> +
섹션별로 줄바꿈 하는 습관이 있는데 깜빡하고 공백을 지우지 않았네요..! 수정할게요 :)

2024-01-11 17:48 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ProductImage/ProductImage.styles.ts
헉 Card도 사이즈가 있는 줄 몰랐네요 그럼 디자인 시스템에 명시가 되어 있으니까 Card만 따로 공용 컴포넌트에서 모듈화하고 사용하시는 거 어떠신가요 ? 저 Card 좀 자주 사용되는 거 같아서요~!

2024-01-11 17:49 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
네네 맞습니다! 헤더 보시면 닫기 버튼 이여서 모달로 생각해서 모달로 작성했습니다.
저도 쿠폰리스트로 라우팅 한 번 더 들어가는게 자연스럽다고 생각해요 ㅎㅎ!

2024-01-11 17:55 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/Button/Button.tsx
다 다르게 되어 있는 거 맞죠! 근데 아래 디자인 시스템으로 명시되어 있는 버튼들 공용 컴포넌트로 모듈화하면 해결할 수 있는 것들 아닌가요 ..?

<img src="https://github.com/shophubkr/shophub-client/assets/112946860/b6b5b32b-019e-4d51-b96a-d2d352a0dacd" width="300" />

제가 코드를 엄청 상세히 본 건 아니지만 적어도 아래 이미지에 보이는 버튼 4개는 다 해결할 수 있을 거 같습니다..!

<img src="https://github.com/shophubkr/shophub-client/assets/112946860/8d628787-1383-423d-89a1-cd9cc6cb2b70" width="300" />

어떻게 생각하시나요..?

2024-01-11 17:56 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
> +import type { EssentialModalProps } from "@shophub/ui/src/Modal/Modal.types";
아 헉 확인했습니다. 이런 편리한 방법이 있다니,,
컨텍스트 모달 검색 했을 때 그냥 상태관리 편하게 만들어둔 코드구나 라고 얕게 보고 얕게 생각하고 넘어갔었네요,,
감사합니다 :)

2024-01-11 17:58 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponListModal/CouponListModal.tsx
오른쪽 상단에 x 아이콘 대신에 좌측 상단에 `<`이 좀 더 자연스러울 거 같긴 하네요~~ 디자이너분께 문의 드려보죠~

2024-01-11 18:00 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +          style={{ font: theme.FONTS.p14r }}
그때 폰트 어떻게 적용하셨었는지 기억이 잘 안나는데 css로 하셨었나요? 일단 style 프로퍼티 통해 폰트 바꾸는 부분은 다 지워주셔도 될 거 같아요 저도 폰트 한번도 따로 이용한 적은 없어서 준혁님께서만 다 지워주시면 될 거 같아요~

혹시 저 style 부분 없어지면 큰 이슈 발생하나요?

2024-01-11 18:01 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
저도 길어지면 어쩌나 했었는데 극초반에 회의 했었을 때 그냥 적기로 했었습니다~

준혁님께서도 최대한 Chakra 사용해주시는 게 좋을 거 같아요 👍 길어져도 상관 없습니다~

2024-01-11 18:01 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/Button/Button.tsx
<img width="809" alt="image" src="https://github.com/shophubkr/shophub-client/assets/150168223/2eb9c566-4cca-4d91-a54b-b12e8b8ba7f0">

제 담당 페이지에서는 코드가 길어지지 않을 것 같은데,
라지 버튼 보시면 디자인이 너무 각각이라 코드가 길어질 것 같아서요.
그러고보니 버튼 디자인 시스템이 2개네요...?

2024-01-11 18:08 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/Button/Button.tsx
제가 봤을 때는 bgColor랑 textColor만 다르고 default랑 pressed 이렇게 2개씩 나온 게 다 인 것 같아요~!
시간되면 제가 먼저 Button 공용 컴포넌트 모듈화 하고, 그걸로 리팩터링 해보시는 건 어떠신가요 ?

2024-01-11 18:13 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
근데 그러면 이모션 라이브러리는 packages 작업 환경에서 사용하는 부분 빼고는 일절 사용하지 않는건가요?
이렇게 작업하면 client - package.json 디펜던시에 없어도 될 것 같아서요!

2024-01-11 18:15 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
> 근데 그러면 이모션 라이브러리는 packages 작업 환경에서 사용하는 부분 빼고는 일절 사용하지 않는건가요?

저는 진짜 app에서는 한번도 안 썼습니다....

> 이렇게 작업하면 client - package.json 디펜던시에 없어도 될 것 같아서요!

당장 굳이 없앨 거까지 아닌 거 같아요! 그건 나중에 해도 되니까요! 후순위로 미뤄도 될 거 같아요~

2024-01-11 18:22 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +          style={{ font: theme.FONTS.p14r }}
![image](https://github.com/shophubkr/shophub-client/assets/150168223/e30842ed-9edf-4ec2-b40f-1163d32e72ff)
![image](https://github.com/shophubkr/shophub-client/assets/150168223/f3f3dda5-f6bd-4200-a713-b5c28745ec31)
~~이모션으로 작업 한 부분들은 전부 theme를 props로 줘서 폰트 / 색상 처리 했습니다!~~

~~이슈 발생하는건 딱히 없고 순전히 디자인에 맞춰 퍼블 1차 작업했습니다!~~
~~지금 삭제 커밋 날리는 것 보다는, 추후 작업 할 때 chakra theme와 연결되면 삭제 + 수정해서 1개의 커밋으로 날리는게 낫지 않을까 라는 생각인데 어떻게 생각하시나요?~~

~~* style 프로퍼티 사용하는 부분 이 코드밖에 없긴 합니다 ㅎㅎ,, 다 이모션으로 작성해서요~~

이모션 -> 차크라 변경하는 작업 할게요!

2024-01-11 18:35 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
어,, 해당 사항 반영할 때 제 코드도 전부 chakra로 바꾸게 되면 바꾸는 김에 삭제해서 PR 보내도 될 것 같아서요!
확인했습니다 일단 그럼 제 코드만 수정 할게요~

2024-01-11 18:36 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/Button/Button.tsx
네 확인했습니다

2024-01-13 14:17 UTC, showme0241 reviewed
고생하셨습니다. 준혁님

이미 도은님이 상세하게 리뷰를 해주셔서 동일한 리뷰는 패스하고 일부 리뷰와 총평으로 대체 하겠습니다.

1. jsx 태그와 차크라와 스타일 컴포넌트들이 많이 혼용 되어 있었습니다. 특수한 경우를 제외하고, 차크라로 구조를 잘 짜시면 많은 css 코드(style file, import type)가 줄어질 것 같고, props 관리도 편해지실 것 같습니다.

가끔 차크라가 작동이 안되는 스타일 요소들이 생겼던 경험이 있는데 그런 경우를 특수한 경우로 언급했습니다.

2. Button 컴포넌트가 모듈로서 제약 사항이 보입니다. 기능 상세에 대해서는 도은님이 말씀주신 것 같애요. 저도 작년에 동일한 걸로 고생했었는데... 이벤트 핸들러가 받는 props는 특수한 경우를 제외하고는 대부분 비슷하더 라구요. 특히, 모듈화된 컴포넌트 안에 상수로 관리되는 로직이 있으면 독립성이 떨어져 유지보수할 때 어렵더 라구요.

3. 스타일 요소 중 사이의 간격을 { gap : 4px } 표현해 주셨더라구요. flex | grid 는 많이 사용되는 요소라서 개인적으로 행인지 열인지 코드 보고 UI를 캐치할 수 있게 row-gap, column-gap으로 사용하고 있어요. 참고하시면 좋을 것 같아요.

2024-01-13 14:17 UTC, showme0241 commented on apps/client/src/app/shop/[shopid]/page.tsx
> +      <ShopDetailInfo />
ShopOperationInfo 라는 이름은 어떠실까요?? 매장 상세 정보 보다는 매장 운영 정보가 조금 더 자연스럽게 보입니다. 참고해주세요 👍

2024-01-13 14:17 UTC, showme0241 commented on apps/client/src/app/shop/[shopid]/page.tsx
> +      </Flex>
20번줄 부터 28번줄 까지를 컴포넌트로 추상화 하는 것이 ShopDetailInfo, CouponSection, ShopProductSection 컴포넌트를 추상화하신 의도와 부합될 것 같습니다. 👍

2024-01-13 14:22 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +          style={{ font: theme.FONTS.p14r }}
저희가 폰트에 대해서 자세하게 의논한 적은 없어서 폰트 적용 부분은 제외하고 수정해주시면 될 것 같습니다 👍

2024-01-14 06:15 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/page.tsx
> +      <ShopDetailInfo />
확인했습니다!

2024-01-14 06:16 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/page.tsx
> +      </Flex>
공유 팔로우 버튼들이 있어 같이 추상화 해도 될 까 싶었는데,, 감사합니다!

2024-01-14 08:09 UTC, Doeunnkimm requested changes
추가 반영 부탁드립니다 준혁님~!

고생하셨습니다

2024-01-14 08:09 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +        </span>
Icon 컴포넌트에 대해 모듈화 하는 건 좋으나 [코멘트](https://github.com/shophubkr/shophub-client/pull/35#discussion_r1449003855) 남겨드린 것처럼 하면 좀 더 유용할 것 같다고 말씀 드렸었는데 이 부분 누락된 것 같네요 😅

반영 부탁드립니다~!!!

2024-01-14 08:09 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
> +      <Image boxSize="358px" borderRadius="8px" src="https://picsum.photos/200" alt="Shop Thumbnail Images" />
이건 `next/image`의 Image 컴포넌트 사용 안 하시는걸까요 ? 이유가 궁금합니다~

2024-01-14 08:09 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopProductSection/ShopProductSection.styles.ts
이 파일 제거 부탁드립니다~~!

2024-01-14 08:09 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopProductSection/ShopProductSection.tsx
> +          <Image src="https://picsum.photos/200" alt="Product Image" borderRadius="8px" w="172px" h="172px" />
여기도 next/image의 Image 컴포넌트를 사용하지 않으신 이유에 대해 궁금합니다~

2024-01-14 08:09 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_states/client/couponModal.state.ts
이 파일도 제거되어도 될 것 같네요 👍

2024-01-14 08:09 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/layout.tsx
> +    <Container w="390px" p="16px">
width는 빠지고 padding만 해줘도 되지 않을까요 ?

2024-01-14 08:09 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/page.tsx
> +      <Flex columnGap="14px" m="24px 0">
상하만 margin을 주는 것을 의도하셨다면 `my="24px"`로 하시면 좋을 거 같아요 👍

2024-01-14 08:09 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopProductSection/ShopProductSection.tsx
> +          <Text m="8px 0 16px 0" fontSize="14px" fontWeight="300">
```suggestion
          <Text mt="8px" mb="16px" fontSize="14px" fontWeight="300">
```
이게 좀 더 깔끔한 것 같은데 어떠신가요 ?

2024-01-14 11:51 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/CouponSection/CouponSection.tsx
> +        </span>
아 확인했습니다!
아이콘은 다른 페이지들에서도 쓰이니 app - components 폴더에 모듈화시킬게요!

2024-01-14 11:53 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
> +      <Image boxSize="358px" borderRadius="8px" src="https://picsum.photos/200" alt="Shop Thumbnail Images" />
myapp 작업하신 코드 봤을 때 Image 태그 사용하지 않으시고 Chakra Avatar 태그 사용하셔서 이미지 태그들도 Chakra 태그들로 사용하는 줄 알았습니다! 혹시 아니였을까요..?

2024-01-14 12:00 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
> +      <Image boxSize="358px" borderRadius="8px" src="https://picsum.photos/200" alt="Shop Thumbnail Images" />
가게 정보 같은 건 next/image의 Image 컴포넌트 사용했어요! Avatar는 그냥 그 그대로 갖다써서,, 😅

2024-01-14 12:05 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ShopProductSection/ShopProductSection.tsx
> +          <Text m="8px 0 16px 0" fontSize="14px" fontWeight="300">
margin X / Y 축 옵션이랑 top, bottom, left, right에서 2가지 이상 작성할 때는 저 방식이 코드 유지보수에는 편하다고 느껴서 항상 저렇게 작성했습니다..!
차크라 방식에서는 작성 해주신 코드가 더 가독성은 좋아보이긴 하네요! 수정할게요 :)

2024-01-14 12:06 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
> +      <Image boxSize="358px" borderRadius="8px" src="https://picsum.photos/200" alt="Shop Thumbnail Images" />
악 ㅋㅋㅋ 확인했습니다! 그러면 next/image Image태그로 수정할게요!

2024-01-14 12:08 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ShopBriefInfo/ShopBriefInfo.tsx
> +      <Image boxSize="358px" borderRadius="8px" src="https://picsum.photos/200" alt="Shop Thumbnail Images" />
아 저도 기존에 Image 태그 사용해서 작성할 때 부모 컴포넌트로 한 번 묶어줘서 사용해야하던데, 이 부분 모듈화 하시는건 어떻게 생각하시나요?

2024-01-18 06:59 UTC, Doeunnkimm reviewed
준혁님~~ 주로 ImageBox에 대해 의견이 좀 있어서 코멘트 남겨보았어요 🧐

다른 건 피드백 잘 반영해 주셔서 감사합니다 🙇🏻

2024-01-18 06:59 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopProductSection/ShopProductSection.tsx
<img width="400" alt="image" src="https://github.com/shophubkr/shophub-client/assets/112946860/ef3cabad-cac7-4d05-b70f-60e5abcf853c">

준혁님! 위에 부분 자식 컴포넌트로 한번더 추상화해서 해당 컴포넌트에서 데이터 배열 받아서 map 돌리는 로직까지 미리 구상하시면 나중에 api 연결 시 수월할 거 같은데 어떠신가요 ?

2024-01-18 06:59 UTC, Doeunnkimm commented on apps/client/src/components/Icon/Icon.types.ts
> +  size: number;
size는 default로 16이 들어가기도 해서 optional하게 받는 거 어떠신가요 ?

2024-01-18 06:59 UTC, Doeunnkimm commented on apps/client/src/components/Icon/Icon.stories.tsx
> +};
준혁님! 스토리북에서 해당 부분은 default로 설정하고 들어갈 것들을 명시하는 경우가 많은 거 같아요!

그래서 해당 부분에서 작성하신 건 아래에서 

```tsx
export const Basic: Story = {
  args: {
    name: 'sell', // google-material-icons에 명시되어 있는 name을 전달
  }
}

export const SetSize: Story = {
  args: {
    ...Basic.args,
    size: 20
  }

export const setColor = {
  args: {
    ...Basic.args,
    color: ...
  }
}
}
```

저는 이런 식으로 모듈화한 내용에 대해 다른 개발자와 공유하기 좋게 작성하는 걸 좋아하는데 어떠신가요 ?!

2024-01-18 06:59 UTC, Doeunnkimm commented on apps/client/src/components/ImageBox/ImageBox.types.ts
저희가 이 컴포넌트를 만들어 쓰기로 했던 이유가 next의 image 가장자리에 스타일을 편하게 넣기 위해서라고 이해했는데요!
그렇다면 확장성을 위해 `extends BoxProps`가 맞다고 생각이 들어서 아래와 같이 수정해 보았는데 어떠신가요 ?

```tsx
import type { BoxProps } from "@chakra-ui/react";
import type { ImageProps } from "next/image";

type ImgOptionsProps = Omit<ImageProps, "src" | "alt">;

export interface ImageBoxProps extends BoxProps {
  src: ImageProps["src"];
  alt: ImageProps["alt"];
  imgOptions: ImgOptionsProps;
}
```

이렇게 하면 스타일적으로 제약도 없이 좀 편하게 유연하게 사용할 수 있을 거 같아요!

2024-01-18 06:59 UTC, Doeunnkimm commented on apps/client/src/components/ImageBox/ImageBox.stories.tsx
```tsx
import type { Meta, StoryObj } from "@storybook/react";

import { ImageBox } from "./ImageBox";

const meta: Meta<typeof ImageBox> = {
  title: "client/components/ImageBox",
  component: ImageBox,
};

export default meta;

type Story = StoryObj<typeof ImageBox>;

export const Custom: Story = {
  args: {
    src: "https://picsum.photos/200",
    alt: "test_image",
    borderRadius: "10px",
    boxSize: "358px",
  },
};
```

여기도 제가 좀 수정해 보았는데 어떠신가요 ?!
Chakra에 boxSize로 넘기면 정사각형 되더라구요 🧐 (저도 첨 알았..

2024-01-18 06:59 UTC, Doeunnkimm commented on apps/client/src/components/ImageBox/ImageBox.tsx
```tsx
import Image from "next/image";
import { Box } from "@chakra-ui/react";

import type { ImageBoxProps } from "./ImageBox.types";

export const ImageBox = ({ src, alt, imgOptions, ...boxStylesProps }: ImageBoxProps) => {
  return (
    <Box position="relative" overflow="hidden" {...boxStylesProps}>
      <Image src={src} alt={alt} fill sizes="100%" {...imgOptions} />
    </Box>
  );
};
```

제가 말씀드린 내용대로 반영해본다면 위와 같을 거 같아요~~ 혹시 괜찮다고 생각 드시면 참고해보셔도 좋을 거 같습니다 !

2024-01-18 09:12 UTC, CodImJun commented on apps/client/src/app/shop/[shopid]/_components/ShopProductSection/ShopProductSection.tsx
@Doeunnkimm 
해당 부분은 디자인 시스템 카드 컴포넌트로 들어가서요!
그래서 package 스페이스에 ImageBox를 모듈화 해야하나,, 생각이 들었는데 어떻게 하는게 좋다고 생각하시나요?

2024-01-18 09:12 UTC, CodImJun commented on apps/client/src/components/Icon/Icon.types.ts
> +  size: number;
네 좋습니다!

2024-01-18 09:28 UTC, CodImJun commented on apps/client/src/components/Icon/Icon.stories.tsx
> +};
오 좋습니다! 컴포넌트 타입(?)을 나눌게 있나,,, 생각하다 떠오르지 않아서 그냥 default 하나만 작성했는데,,
크기나 컬러 지정하는 부분도 모듈화 해도 되겠네요!
맨날 도은님 덕분에 좋은 방식을 배워가는 것 같네요,, 감사합니다!

2024-01-19 12:51 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shopid]/_components/ShopProductSection/ShopProductSection.tsx
ui 패키지에는 client랑 admin 둘다에서 사용될 컴포넌트를 모듈화하는 공간이라고 생각합니다~!
또 그게 아니더라도 ui 페키지에는 next가 없습니다 🤔 !

2024-01-22 09:35 UTC, Doeunnkimm approved these changes

2024-01-22 11:59 UTC, merged