회원가입 입력 정보를 서버로 전송하기 위해 API를 추가 합니다.
shophubkr/shophub-client pull request #45
Opened 2024-01-23 01:53 UTC by showme0241

# Describe your changes
1. SignUpSecond 컴포넌트 리팩토링 : 컴포넌트 추상화
2. 서버 통신을 위함 훅함수 추가 : usePostSignUp
3. submit 데이터 관리와 통신 역할을 하는 훅함수 추가 : useSignUpSubmitHandler

## Issue ticket number and link (optional)

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
1. API 통신 테스트 및 검증
2. 퍼블리싱 보강 - 디자인 시스템 적용

## Screenshots (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2024-01-24 07:35 UTC, CodImJun commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +export const usePostUserSignUp = () => {
회원가입 요청을 보내고, 성공 여부에 따른 모달 띄우는 훅이 맞을까요?
해당 기능이 맞으면.. 당장 생각나는 훅 명은 `useUserSignUpWithModal`나 `useSignUpRequestAndModal`이  조금 더 직관적이지 않을까 의견을 내봅니다!

2024-01-24 07:35 UTC, CodImJun commented on apps/client/src/app/auth/_state/server/api.ts
>  export const LoginApi = {
카멜 케이스와 파스칼 케이스 두 가지가 보입니다!
카멜 케이스로 통일하는게 좋아보입니다 :)
```suggestion
authApi / loginApi
```

2024-01-27 14:58 UTC, showme0241 commented on apps/client/src/app/auth/_state/server/api.ts
>  export const LoginApi = {
아 제 실수입니다! 수정해놓겠습니다.
본 작업은 sign-up 브랜치 pr 완료 후, login 브랜치에서 정정해놓도록 하겠습니다. 😄

2024-01-27 15:00 UTC, showme0241 commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +export const usePostUserSignUp = () => {
좋은 의견입니다! 다만, 이번 기획 재정비 때 변경된 플로우가 있어서 해당 post 훅에서는 모달을 사용하지 않을 예정입니다. 의견 감사합니다 👍

2024-01-28 11:45 UTC, minsoo-web requested changes
리뷰 남겼습니다~!

2024-01-28 11:45 UTC, minsoo-web commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +      return res.data;
#51 PR이 머지가 되면 이 부분도 수정이 되어야 하는데요, 51 PR의 res?.data.result 이 부분을 삭제하고

```suggestion
      const { data } = await authApi.signUp(userInfo);

      return data.result;
```

이렇게 하면 됩니다.

2024-01-28 11:45 UTC, minsoo-web commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +    }
usePostUserSignUp 에서 onError 처리를 했기 때문에 try-catch를 쓸 필요가 없어보입니다~!

2024-01-28 11:45 UTC, minsoo-web commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +  const onSubmitHandler = async (data: SignUpFormValues) => {
await 를 할 필요가 없기 때문에 async 함수 일 필요도 없습니다.

2024-01-29 05:05 UTC, Doeunnkimm reviewed
고생하셨습니다~~!! 👍

2024-01-29 05:05 UTC, Doeunnkimm commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +  const { isLoading, mutateAsync } = useMutation(
여기서 구조분해 해서 return 하는 형태가 아니라 useMutation 자체를 return 해줘서 사용하는 쪽에서 필요한 걸 사용하는 건 어떤가요 ?

2024-01-29 05:05 UTC, Doeunnkimm commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +        data?.result?.id &&
요건 왜 필요한건가요 ?!

2024-01-29 05:05 UTC, Doeunnkimm commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +  const { isLoading, mutateAsync } = usePostUserSignUp();
그냥 mutate 사용하셔서 버튼 클릭했을 때 데이터 넘기기만 하면 됩니다! 

그리고 해당 파일로 해당 로직들을 분리하신 이유가, 데이터 전송과 관련된 부분을 View 로직과 분리하고 싶으셔서? 라고 예측이 되는데!! 
원래 파일에서 hook-form으로 관리하고 있던 데이터 가지고 버튼 누르면 mutate로 보내기만 하면 되니까 !
저는 굳이 분리 안 해도 될 거 같은데 태찬님 의견은 어떠신지 궁금해요~!

2024-01-30 07:14 UTC, showme0241 commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +        data?.result?.id &&
해당 코드 작성할 때 즈음 api 응답에 result에 다른 값도 있는 경우가 있어서 가드했던 것 같습니다. 재확인 해봐야할 것 같아요 😄

2024-01-30 08:07 UTC, showme0241 commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +  const { isLoading, mutateAsync } = usePostUserSignUp();
mutate를 사용하는 것이 더 좋은 방향이네요. mutate와 mutateAsync 내부 로직을 볼 기회가 되었습니다. 👍 
네 예측하신게 맞습니다. 제출한 데이터 중 일부 데이터를 추출하고 buyer와 seller에 따라서 서버로 전송할 데이터에 구분해야줘야해서 동작에 필요한 부가적인 코드라 뷰단이랑 로직을 나누려고 했습니다.

hook-form의 watch를 이용하여 일부 데이터를 따로 선언해놓은다면 뷰단이랑 로직을 나누지 않아도 될것 같습니다.
추가 의견주시면 참고해보겠습니다. 😄

2024-02-01 08:19 UTC, Doeunnkimm reviewed
리뷰 사알짝 남겨봅니당 🫢

2024-02-01 08:19 UTC, Doeunnkimm commented on apps/client/src/app/auth/_state/server/api.ts
> +    return data.result;
`Request`라는 프로퍼티명이 뭔가 살짝 불편하기도 한게, 호옥시 모를 나중을 위해 좀 더 명시적으로 쓰는 건 어떨까요 ? 
그렇게 마음에 들진 않지만.. 앞에 어떤 요청인지 조금 붙이면 `postSignup` 정도도 나쁘지 않을 거 같아용

2024-02-01 08:19 UTC, Doeunnkimm commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +  );
저는 객체로 작성하는 거 선호하긴 하는데 어떠신가요 ? `mutationFn` 으로 명시적으로 넣어줬어요!
아, 그리고 `mutationFn: (userInfo: SignUpFormValues) => API_SIGN_UP.Request(userInfo)`처럼 async/await 떼도 정상 동작합니다!

테스트할 겸 요청 보내봤는데, 회원가입 성공하고 어디론가 보내주면(ex. 로그인하러?) 좋을 거 같아요~~!

그리고!! Modal 조금 수정한 거 반영했어용 onConfirm 보내지 않으면 확인 눌렀을 때 닫히는 액션만 하게 됩니당

```suggestion
  return useMutation({
    mutationFn: (userInfo: SignUpFormValues) => API_SIGN_UP.Request(userInfo),
    onSuccess: () =>
      modal.open({
        title: "회원가입이 완료되었습니다.",
        type: "positive",
        onConfirm: () => alert("회원가입 완료"),
      }),
    onError: (error) =>
      modal.open({
        title: "회원가입을 실패하였습니다.",
        type: "negative",
        onConfirm: () => alert(error),
      }),
  });
```

2024-02-01 08:19 UTC, Doeunnkimm commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +  return { onSubmitHandler, isLoading };
isLoading은 왜 필요한가용 ? 나중에 mutate 관련되어서 필요할 수도 있을 거 같아서라고 생각이 되는데

그렇다면 위에서

```tsx
const { mutate, ...나머지들 } = usePostUserSignUp();
...
reutrn { onSubmitHandler, 나머지들 }
```

해서 사용하면 오히려 좋을 거 같아용 🤔

2024-02-01 08:30 UTC, minsoo-web commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +  return { onSubmitHandler, isLoading };
저는 이 훅이 따로 필요한가? 라는 의문이 있습니다. 
usePostUserSignUp  만 필요한 곳에서 import 하면 된다고 생각하기에, 불필요한 wrapper가 또 생성된 게 아닐까 싶습니다

2024-02-01 08:33 UTC, minsoo-web commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +  );
이거는 제가 다른 리뷰에도 남겼는데, react-query 버전업이 되면 사용할 수 없는 인터페이스라 미리 객체로 다 변환하는 것도 좋을 것 같아요, eslint 도 추가하는 것을 추천드립니다
https://github.com/shophubkr/shophub-client/pull/52#discussion_r1473720801

2024-02-01 08:33 UTC, minsoo-web commented on apps/client/src/app/auth/_types/signUpResponse.type.ts
회원가입 response 를 client에서 사용하나요??? 불필요한 타입 선언은 아닐지 궁금합니다 🤔

2024-02-01 08:56 UTC, showme0241 commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +  return { onSubmitHandler, isLoading };
@minsoo-web 
의문이라고 말씀주시니 고민해보겠습니다 👍 

혹시 새로운 훅에 감싸게 되면 불필요하다라고 생각하시는 이유가 있으실까요?

1. 뷰
2. 통신
3. 제출 데이터 필터링
=> 역할을 분리하면 코드 관리가 더 이롭지 않을까 하는 개인 의견이 있습니다.

2024-02-02 06:24 UTC, showme0241 commented on apps/client/src/app/auth/_types/signUpResponse.type.ts
엇! 너무 불필요합니다 컨벤션에 매몰되서 생각없이 선언한 것 같네요 ㅠㅠㅠㅠ

2024-02-02 07:08 UTC, showme0241 commented on apps/client/src/app/auth/_state/server/hooks/usePostSignUp.ts
> +        onConfirm: () => router.push("/"),
회원가입 후, 자동 로그인이 될 예정이기 때문에 루트로 라우팅 합니다. 😄

2024-02-02 07:18 UTC, Doeunnkimm commented on apps/client/src/app/auth/signup/step2/page.tsx
> +  const onSubmitHandler = (data: SignUpFormValues) => {
handle.... 🫢!

2024-02-02 07:53 UTC, showme0241 commented on apps/client/src/app/auth/signup/step2/page.tsx
> +  const onSubmitHandler = (data: SignUpFormValues) => {
handle??

2024-02-04 02:29 UTC, minsoo-web commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +  return { onSubmitHandler, isLoading };
네넵 태찬님, 제가 리뷰에 적어두긴 했는데 다른 표현으로 다시 말씀드려볼게요!!

> usePostUserSignUp 만 필요한 곳에서 import 하면 된다고 생각하기에, 불필요한 wrapper가 또 생성된 게 아닐까 싶습니다
이 hook이 호출 될 때마다 필요한 전처리가 있다면, 작성해주신 대로 하는 것도 방법입니다.
하지만, 이 hook은 회원가입 페이지에서 한 번만 호출되기 때문에 
axios -> useMutate -> usePostUserSignUp -> useSignUpSubmitHandler
이렇게 wrapper 가 wrapper 를 낳는 현상이 발생한거라 생각해서 usePostUserSignUp 하나만 필요한 곳에서 import 하면 된다고 생각했습니다.

> => 역할을 분리하면 코드 관리가 더 이롭지 않을까 하는 개인 의견이 있습니다.
역할을 분리하면 코드 관리가 이로운 건 맞습니다! 다만 해당 리뷰에서는 불필요하게 wrapper를 하나 더 만든 것이라 생각한 리뷰입니다.

2024-02-04 03:37 UTC, showme0241 commented on apps/client/src/app/auth/_state/server/hooks/useSignUpSubmitHandler.ts
> +  return { onSubmitHandler, isLoading };
아! 이해됐습니다  상세하게 답변 주셔서 감사합니다. 👍 
상품 등록 페이지 같은 경우, 낙관적 업데이트 같은 부수적인 동작이 클라이언트에 더 필요한 경우이거나 찜이나 상품 목록 페이지에서 query를 무효화시키고 재호출해야 되는 경우를 고려했을 때는 wrapper를 통해 관리된다면 상황에 맞다라고 볼 수 있는거죠?

2024-02-12 06:12 UTC, merged