버튼 컴포넌트 수정 및 Detail 페이지 API 연동
shophubkr/shophub-client pull request #52
Opened 2024-01-28 15:45 UTC by CodImJun

# Describe your changes
1. 버튼 컴포넌트 tiny 사이즈 CSS의 문제가 있어 수정했습니다.
2. Detail페이지 API 연동했습니다.

## Issue ticket number and link (optional)

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Screenshots (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2024-01-29 05:24 UTC, Doeunnkimm reviewed
react-query 관련 코멘트는 하나 작성했지만, 여러 부분 있는 걸로 확인됩니다~ 리뷰 확인해주시고 모든 부분에 반영부탁드려요~

2024-01-29 05:24 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_components/CouponSection/CouponSection.tsx
> +  const { isLoading, data, isError } = useQuery(["couponInfo", shopId], () => couponApi.getNearestExpiryCoupon(shopId));
보통 query들이나 mutation들은 모듈화해서 사용하는데요! 
모듈화를 해놓은 파일에서 성공/실패 로직을 작성하고, 사용하는 쪽에서는 성공 로직들만 신경쓸 수 있다는 점에서 모듈화 하면 좋아요!

레퍼런스들은 쉽게 찾아볼 수 있어서 한번 찾아보시고 적용해보시면 좋을 거 같아요~~!

2024-01-29 05:24 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_components/CouponSection/CouponSection.tsx
> +  const { isLoading, data, isError } = useQuery(["couponInfo", shopId], () => couponApi.getNearestExpiryCoupon(shopId));
아 추가로, 저희 쿼리키 관리하는 방식에 대해서는 한번 의논을 해야할 거 같네요 😓

2024-01-29 05:24 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_components/CouponSection/CouponSection.tsx
> +  if (isError) return null;
현재 로딩 및 실패 로직에 대해 의논한 건 없으니까~ 나중에 추가해도 될 거 같아요~~~

그리고 추가로..
Next.js에서는 [loading](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming)이랑 [error](https://nextjs.org/docs/app/building-your-application/routing/error-handling)를 컨벤션으로 제공하고 있어요! 저희가 `page.tsx`로 파일을 만들기만 하면 라우팅이 되는 것처럼 말이죠?

그래서 해당 파일에서 로딩/실패 로직을 처리하지 않아도 됩니다.

2024-01-29 05:25 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_states/server/api.ts
> +};
전부 shop과 관련된 api로 보이는데 `shopApi`에 다 넣는게 좋아보이는데 어떠신가요 ?

2024-02-01 02:49 UTC, minsoo-web requested changes
리뷰 남겨봅니다~!!!

2024-02-01 02:49 UTC, minsoo-web commented on apps/client/src/components/Icon/Icon.tsx
> +    <span className="material-icons-outlined" style={{ fontSize: `${size ?? 16}px`, color: `${color}` }}>
size의 defaultValue를 정해주는 건 어떨까요? size를 다른 코드에 사용하게 될 경우에 또 ?? 16 을 붙여줘야 하니, 함수 선언 부에서 defaultParameter 를 지정해주는 게 더 올바른 해결 방법 같습니다.

```tsx
export const Icon = ({ name, size = '16px', color }) => {
```

2024-02-01 02:49 UTC, minsoo-web commented on apps/client/src/app/shop/[shop_id]/_hooks/useGetShopDetailInfo.ts
> +  );
react-query 는 신규 버전부터 객체 형태로만 강제합니다. eslint 를 설치해보시구, 객체 형태로 옵션을 넣는 것을 추천드립니다~!
https://tanstack.com/query/v4/docs/eslint/eslint-plugin-query

2024-02-01 02:49 UTC, minsoo-web commented on apps/client/src/app/shop/[shop_id]/_types/api.types.ts
> +    id: number;
백엔드에서 result 라는 객체로 담아서 보내주는게 컨벤션인 것 같은데, 제네릭으로 BaseResponse 와 같은 타입을 선언해서 wrapper로 사용해보세요!

2024-02-01 02:49 UTC, minsoo-web commented on apps/client/src/app/shop/[shop_id]/page.tsx
> +      )}
로딩이 필요한 ui와 로딩과 관계 없이 노출될 수 있는 ui가 구분지어졌으면 좋겠어요
지금은 전체 페이지가 안 보이다가 뚱 하고 뜰 것 같습니다.
suspense를 적용해서 로딩이 필요한 ui 만 구분 짓는 것은 어떨까요?

2024-02-01 02:49 UTC, minsoo-web commented on packages/ui/src/Button/Button.styles.ts
> +    border-radius: 999px;
999로 바꾸신 이유가 있으신가요?

2024-02-01 02:49 UTC, minsoo-web commented on packages/ui/src/Button/Button.tsx
> +            fontSize: `${props.iconSized ?? 16}px`,
얘도 마찬가지로 ?? 을 쓰는 게 아니라, default parameter 를 적용해보세요!

2024-02-01 02:49 UTC, minsoo-web commented on apps/client/src/app/shop/[shop_id]/_components/ShopProductSection/ShopProductSection.tsx
> +          })}
```suggestion
        {productList && productList.map((product) => <ShopProduct key={product.name + product.id} {...product} />)}
```

return 키워드를 굳이 사용할 필요가 있을까요??

2024-02-01 02:49 UTC, minsoo-web commented on apps/client/src/app/shop/[shop_id]/_components/ShopProduct/ShopProduct.tsx
> +      </div>
```suggestion
      <Box position="absolute" top="8px" right="8px">
        <Icon name="sell" />
      </Box>
```

차크라에는 Box라는 컴포넌트가 있습니다. 인라인 style은 컨벤션에 맞지 않게 휘뚜루마뚜루 느낌이 강해서 차크라의 Box를 사용해 보시는 건 어떨까요?

2024-02-01 07:54 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_hooks/useGetProductsByShop.ts
react-query 관련 hook들은 해당 폴더 보다는 태찬님께서 해주신 것 처럼 아래 경로에 있으면 좀 더 구분해서 보기 좋을 거 같아요~~!

<img src="https://github.com/shophubkr/shophub-client/assets/112946860/0ee6042c-9997-4e4e-af55-aefb01dcb5f6" width="400" />

2024-02-01 07:54 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_hooks/useGetProductsByShop.ts
> +  return productList;
이 부분에 대해서는 태찬님께도 [코멘트](https://github.com/shophubkr/shophub-client/pull/45#discussion_r1469072320) 드렸는데 훅 자체를 return 해서 사용하는 쪽에서 필요할 걸 구조분해 해서 사용하는 게 좋을 거 같아요~

2024-02-03 02:17 UTC, CodImJun commented on packages/ui/src/Button/Button.styles.ts
> +    border-radius: 999px;
@minsoo-web 
full 옵션으로 줄 디자인이 999px 들어간 것 뿐이더라구요!
50%로 주니까 디자인이 아예 깨져버려서 수정했습니다!

2024-02-03 02:24 UTC, CodImJun commented on packages/ui/src/Button/Button.styles.ts
> +    border-radius: 999px;
앗 다시 확인하니 50%, 999px 둘 다 있어야하네요,,, 옵션 따로 추가할게요!

2024-02-03 02:28 UTC, CodImJun commented on apps/client/src/components/Icon/Icon.tsx
> +    <span className="material-icons-outlined" style={{ fontSize: `${size ?? 16}px`, color: `${color}` }}>
헉,, 이상하게 코드 작성을 했었네요... 바로 수정했습니다!

2024-02-03 02:31 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/page.tsx
> +      )}
로딩 ui 관련해서는 디자인이 아직 나오지 않아 추후에 추가하기로 했어서요!
서스펜스랑 에러바운더리 사용해서 추가하겠습니다 :)

2024-02-03 02:37 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_components/ShopProductSection/ShopProductSection.tsx
> +          })}
줄바꿈 때문에 return 사용했었는데 옵셔널체이닝으로 하니 똑같이 작성되네요! 수정했습니다 :)

2024-02-03 03:27 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_hooks/useGetProductsByShop.ts
> +  return productList;
확인했습니다!

2024-02-03 13:04 UTC, Doeunnkimm commented on packages/ui/src/Button/Button.styles.ts
>  };
준혁님 혹시 sizeCSS 부분 아래와 코드처럼 padding 대신에 height로 지정해주실 수 있나요?

```tsx
export const sizeCSS = {
  large: css`
    height: 48px;
  `,
  medium: css`
    height: 40px;
    font-size: 14px;
  `,
  small: css`
    height: 32px;
    font-size: 14px;
  `,
  tiny: css`
    height: 22px;
    font-size: 14px;
  `,
};
```
지금 추가해주신 column-gap은 유지하신 채로 padding -> height로 위와 같이 수정해주시면 감사하겠습니다 🙏

2024-02-03 14:05 UTC, CodImJun commented on packages/ui/src/Button/Button.styles.ts
>  };
확인했습니다!

2024-02-03 14:28 UTC, Doeunnkimm approved these changes
고생하셨습니다~~ 리뷰 하나만 확인 부탁드려용 🙏

2024-02-03 14:28 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_states/server/hooks/useGetNearestExpiryCoupon.ts
> +  const SHOP_ID = Number(params.shop_id);
shop_id 값을 params에서 꺼내서 자주 사용할 거 같은데 커스텀 훅으로 만드는 거 어떨까요?

```tsx
// useShopIdParams

export const useShopIdParams = () => {
  const params = useParams()
  const SHOP_ID = Number(params.shop_id)

  return SHOP_ID
}
```

2024-02-04 04:07 UTC, showme0241 commented on apps/client/src/app/shop/[shop_id]/_states/server/api.ts
> +    return res.data.result.productList;
클라이언트에 필요한 값이 응답 객체의 data 뿐이라면 api 작성은 이렇게 맞추는 것이 어떨까요?

```suggestion
  GetShopDetailInfo: async (shopId: number) => {
    const { data } = await axiosInstance().get<GetShopDetailInfoResponse>(`/shops/${shopId}`);
    return data.result;
  },
  GetNearestExpiryCoupon: async (shopId: number) => {
    const { data } = await axiosInstance().get<GetNearestExpiryCouponResponse>(`/shops/${shopId}/coupons/shortest`);
    return data.result;
  },
  GetProductsByShop: async (shopId: number) => {
    const { data } = await axiosInstance().get<GetProductsByShopResponse>(`/${shopId}/products`);
    return data.result
```

2024-02-04 04:07 UTC, showme0241 commented on apps/client/src/app/shop/[shop_id]/_components/ShopProduct/ShopProduct.tsx
> +        {price}원 ~
price값이 number 타입으로 응답되는 것으로 알고 있는데 화면에서는 3자리 숫자마다 콤마를 찍어 표기해줘야 할 것 같습니다. 확인 한 번 부탁드립니다. 😄 

```suggestion
        {price.toLocaleString()}원 ~
```

2024-02-04 04:07 UTC, showme0241 commented on apps/client/src/app/shop/[shop_id]/_states/server/hooks/useGetProductsByShop.ts
> +    queryKey: ["productsByShop", SHOP_ID],
query key를 관리할 포맷이 필요할 것 같아 보입니다.

@Doeunnkimm @CodImJun 
각 도메인별 constants > keys 폴더에서 관리하는 것이 어떨지 여쭤봅니다.

```
const QUERY_KEY = {
    PRODUCTS_BY_SHOP : "PRODUCT_IN_SHOP" (주체_조사_대상)
    DETAILS_OF_SHOP : "DETAILS_OF_SHOP"
}
```

2024-02-04 05:28 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_states/server/api.ts
> +    return res.data.result.productList;
@showme0241 
해당 부분은 #56 머지 완료되면 같이 수정 후 푸쉬하겠습니다!

2024-02-04 05:39 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_states/server/hooks/useGetProductsByShop.ts
> +    queryKey: ["productsByShop", SHOP_ID],
@showme0241 
도메인 별 파일보다는 app > constants > keys 폴더에서 관리하는게 좋지 않을까요?
변수명도 `export const QUERY_KEY = {}` 식으로 매번 똑같이 정의할텐데 클라이언트 스페이스에서 중앙 집중 관리하는게 좋지 않을까해서요!

2024-02-04 05:43 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_states/server/hooks/useGetNearestExpiryCoupon.ts
> +  const SHOP_ID = Number(params.shop_id);
@Doeunnkimm 
[chore: params shop_id 커스텀 훅으로 변경](https://github.com/shophubkr/shophub-client/pull/52/commits/192e81a2748da7380b6037f5d8a8e964e856f965)
커스텀 훅으로 변경했습니다! :)

2024-02-04 05:43 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_components/ShopProduct/ShopProduct.tsx
> +        {price}원 ~
@showme0241 
[feat: 콤마 코드 추가](https://github.com/shophubkr/shophub-client/pull/52/commits/ec47c4adf77fac16da7a77ddd8dcb28774ff3100)
확인하고 수정했습니다!

2024-02-04 13:45 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_states/server/hooks/useGetProductsByShop.ts
> +    queryKey: ["productsByShop", SHOP_ID],
[React Query Key 관리](https://www.zigae.com/react-query-key/) 하는 방식에 대한 포스팅인데 해당 방식을 적용한 프로젝트도 몇몇 본 거 같아용 더 좋은 레퍼런스 찾으시면 공유해주셔도 좋습니닷 👍

2024-02-04 13:47 UTC, Doeunnkimm commented on apps/client/src/app/shop/[shop_id]/_states/server/hooks/useGetNearestExpiryCoupon.ts
> +  const SHOP_ID = Number(params.shop_id);
확인했습니다~ 근데 이 hook은 `@/hooks` 폴더에 들어가면 더 좋을 거 같은데 어떻게 생각하시나요 🤔

2024-02-04 16:07 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_states/server/hooks/useGetNearestExpiryCoupon.ts
> +  const SHOP_ID = Number(params.shop_id);
앗 좋습니다! 둘러보니 다른 페이지에도 해당 훅 사용하는 api가 있네요 ㅎㅎ,,,

2024-02-04 16:09 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_states/server/hooks/useGetNearestExpiryCoupon.ts
> +  const SHOP_ID = Number(params.shop_id);
[chore: useShopId 위치 변경](https://github.com/shophubkr/shophub-client/pull/52/commits/408482bc2c5f375d7f1002bda00275901e372b21)

2024-02-07 01:58 UTC, CodImJun commented on apps/client/src/app/shop/[shop_id]/_states/server/api.ts
> +    return res.data.result.productList;
[chore: api 타입 변경](https://github.com/shophubkr/shophub-client/pull/52/commits/080d873b47852cf7d15c75cb39da5fe7e6137271)

2024-02-07 02:58 UTC, Doeunnkimm commented on packages/ui/src/Button/Button.tsx
> +          }}
준혁님 혹시 여기 저번에 모듈화하셨던 Icon 컴포넌트로 리팩터링 부탁드려도 될까요 🙏

2024-02-07 07:23 UTC, CodImJun commented on packages/ui/src/Button/Button.tsx
> +          }}
packages 패키지가 apps에서 재사용 되는 모듈을 작성해두는 스페이스라고 생각되는데,
apps 스페이스에서 packages로 거꾸로 올라가는건 엇나간 패턴이라고 생각되는데 어떻게 생각하시나요?
괜찮다고 생각되시면 패키지 추가하고 올릴게요!

2024-02-07 07:28 UTC, Doeunnkimm commented on packages/ui/src/Button/Button.tsx
> +          }}
아 파일 안 보고 Icon 컴포넌트만 생각했네요,, 리팩터링 없이 그대로 가면 될 거 같습니다~

2024-02-07 12:23 UTC, merged